/*
 * FILE : ../src/fox.cpp
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Build 883)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a) __declspec(dllexport) a
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a) a _export 
#	else
#	    define SWIGEXPORT(a) a 
#	endif
#   endif
#else
#   define SWIGEXPORT(a) a 
#endif

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void SWIG_MakePtr(char *, void *, char *);
extern void SWIG_RegisterMapping(char *, char *, void *(*)(void *));
extern char *SWIG_GetPtr(char *, void **, char *);
extern char *SWIG_GetPtrObj(PyObject *, void **, char *);
extern void SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
extern PyObject *SWIG_newvarlink(void);
#ifdef __cplusplus
}
#endif
#define SWIG_init    initfoxc

#define SWIG_name    "foxc"

#include "fx.h"
#include "fx3d.h"
#include "FXCURCursor.h"
#include "FXJPGImage.h"
#include "FXJPGIcon.h"
#include "FXPNGIcon.h"
#include "FXPNGImage.h"
#include "FXTIFIcon.h"
#include "FXTIFImage.h"
#include "FXRGBIcon.h"
#include "FXRGBImage.h"
#include "FXICOIcon.h"
#include "FXICOImage.h"
#include "FXPyApp.h"
#include "FXPy.h"

static PyObject* messageTypeNames = NULL;

/* Adds a new list object, containing the names of FOX message types */
void FXPy_InitLists(PyObject* dict) {
  if(!messageTypeNames){
    /* Create the list */
    messageTypeNames = PyList_New(SEL_LAST);
    for (int i = 0; i < SEL_LAST; i++) {
      PyList_SetItem(messageTypeNames, i, PyString_FromString(FXDebugTarget::messageTypeName[i]));
      }
    }
  }

static PyObject* l_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyList_Check(target)) {
            o2 = target;
            target = PyList_New(0);
            PyList_Append(target, o2);
	    Py_XDECREF(o2);
        }
        PyList_Append(target,o);
	Py_XDECREF(o);
    }
    return target;
}

static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                         
        if (!PyTuple_Check(target)) {
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

void setErrorObject(PyObject *errorObject) {
	FXbool doSave = FXPyRestoreThread();
	Py_INCREF(errorObject);
	FXPySaveThread(doSave);
	FXPyApp::errorObject = errorObject;
}

unsigned int
_MKUINT(unsigned short l, unsigned short h) {
  return MKUINT(l, h);
}

unsigned int
_SELTYPE(unsigned int s) {
    return SELTYPE(s);
}

unsigned int
_SELID(unsigned int s) {
    return SELID(s);
}

FXuchar
_FXBITREVERSE(FXuchar b) {
    return FXBITREVERSE(b);
}

unsigned long
_FXRGBA(unsigned int r, unsigned int g, unsigned int b, unsigned int a) {
    return FXRGBA(r,g,b,a);
}

FXColor _FXRGB(unsigned int r,unsigned int g,unsigned int b) {
  return FXRGB(r,g,b);
  }

FXuchar _FXREDVAL(FXColor rgba) {
  return FXREDVAL(rgba);
  }

FXuchar _FXGREENVAL(FXColor rgba) {
  return FXGREENVAL(rgba);
  }

FXuchar _FXBLUEVAL(FXColor rgba) {
  return FXBLUEVAL(rgba);
  }

FXuchar _FXALPHAVAL(FXColor rgba) {
  return FXALPHAVAL(rgba);
  }

FXuchar _FXRGBACOMPVAL(FXColor rgba, FXuchar comp) {
  return FXRGBACOMPVAL(rgba, comp);
  }

extern "C" SWIGEXPORT(void initcontainersc());
extern "C" SWIGEXPORT(void initcontrolsc());
extern "C" SWIGEXPORT(void initdialogsc());
extern "C" SWIGEXPORT(void initdirlistc());
extern "C" SWIGEXPORT(void initfox3dc());
extern "C" SWIGEXPORT(void initgraphicsc());
extern "C" SWIGEXPORT(void initiconlistc());
extern "C" SWIGEXPORT(void initmdic());
extern "C" SWIGEXPORT(void initmenusc());
extern "C" SWIGEXPORT(void initmiscc());
extern "C" SWIGEXPORT(void inittablec());
extern "C" SWIGEXPORT(void inittextc());
extern "C" SWIGEXPORT(void inittreelistc());
extern "C" SWIGEXPORT(void initwindowsc());
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_fxsleep(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    unsigned int  _arg0;
    char *_kwnames[] = { "n", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:fxsleep",_kwnames,&_arg0)) 
        return NULL;
    fxsleep(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fxfilematch(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXint  _result;
    char * _arg0;
    char * _arg1;
    FXuint  _arg2 = (FXuint ) ((FILEMATCH_NOESCAPE)|(FILEMATCH_FILE_NAME));
    char *_kwnames[] = { "pattern","string","flags", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"ss|i:fxfilematch",_kwnames,&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (FXint )fxfilematch(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxparseaccel(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXHotKey  _result;
    FXchar * _arg0;
    char *_kwnames[] = { "s", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"s:fxparseaccel",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXHotKey )fxparseaccel(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxparsehotkey(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXHotKey  _result;
    FXchar * _arg0;
    char *_kwnames[] = { "s", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"s:fxparsehotkey",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXHotKey )fxparsehotkey(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxfindhotkeyoffset(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXint  _result;
    FXchar * _arg0;
    char *_kwnames[] = { "s", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"s:fxfindhotkeyoffset",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXint )fxfindhotkeyoffset(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_makeHiliteColor(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXColor  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "clr", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:makeHiliteColor",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXColor )makeHiliteColor(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_makeShadowColor(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXColor  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "clr", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:makeShadowColor",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXColor )makeShadowColor(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxgetusername(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXchar * _result;
    FXchar * _arg0;
    FXuint  _arg1;
    char *_kwnames[] = { "result","uid", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"si:fxgetusername",_kwnames,&_arg0,&_arg1)) 
        return NULL;
    _result = (FXchar *)fxgetusername(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_fxgetgroupname(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXchar * _result;
    FXchar * _arg0;
    FXuint  _arg1;
    char *_kwnames[] = { "result","gid", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"si:fxgetgroupname",_kwnames,&_arg0,&_arg1)) 
        return NULL;
    _result = (FXchar *)fxgetgroupname(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_fxgetpermissions(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXchar * _result;
    FXchar * _arg0;
    FXuint  _arg1;
    char *_kwnames[] = { "result","mode", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"si:fxgetpermissions",_kwnames,&_arg0,&_arg1)) 
        return NULL;
    _result = (FXchar *)fxgetpermissions(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_fxgetpid(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXint  _result;
    char *_kwnames[] = {  NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,":fxgetpid",_kwnames)) 
        return NULL;
    _result = (FXint )fxgetpid();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxcolorfromname(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXColor  _result;
    FXchar * _arg0;
    char *_kwnames[] = { "colorname", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"s:fxcolorfromname",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXColor )fxcolorfromname(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fxrgb_to_hsv(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXfloat * _arg0;
    FXfloat * _arg1;
    FXfloat * _arg2;
    FXfloat  _arg3;
    FXfloat  _arg4;
    FXfloat  _arg5;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    PyObject * _argo2 = 0;
    char *_kwnames[] = { "h","s","v","r","g","b", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"OOOfff:fxrgb_to_hsv",_kwnames,&_argo0,&_argo1,&_argo2,&_arg3,&_arg4,&_arg5)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fxrgb_to_hsv. Expected _FXfloat_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fxrgb_to_hsv. Expected _FXfloat_p.");
        return NULL;
        }
    }
    if (_argo2) {
        if (_argo2 == Py_None) { _arg2 = NULL; }
        else if (SWIG_GetPtrObj(_argo2,(void **) &_arg2,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of fxrgb_to_hsv. Expected _FXfloat_p.");
        return NULL;
        }
    }
    fxrgb_to_hsv(*_arg0,*_arg1,*_arg2,_arg3,_arg4,_arg5);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fxhsv_to_rgb(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXfloat * _arg0;
    FXfloat * _arg1;
    FXfloat * _arg2;
    FXfloat  _arg3;
    FXfloat  _arg4;
    FXfloat  _arg5;
    PyObject * _argo0 = 0;
    PyObject * _argo1 = 0;
    PyObject * _argo2 = 0;
    char *_kwnames[] = { "r","g","b","h","s","v", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"OOOfff:fxhsv_to_rgb",_kwnames,&_argo0,&_argo1,&_argo2,&_arg3,&_arg4,&_arg5)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fxhsv_to_rgb. Expected _FXfloat_p.");
        return NULL;
        }
    }
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fxhsv_to_rgb. Expected _FXfloat_p.");
        return NULL;
        }
    }
    if (_argo2) {
        if (_argo2 == Py_None) { _arg2 = NULL; }
        else if (SWIG_GetPtrObj(_argo2,(void **) &_arg2,"_FXfloat_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of fxhsv_to_rgb. Expected _FXfloat_p.");
        return NULL;
        }
    }
    fxhsv_to_rgb(*_arg0,*_arg1,*_arg2,_arg3,_arg4,_arg5);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_fxparsefontdesc(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXbool  _result;
    FXFontDesc * _arg0;
    FXchar * _arg1;
    PyObject * _argo0 = 0;
    char *_kwnames[] = { "fontdesc","string", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"Os:fxparsefontdesc",_kwnames,&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_FXFontDesc_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of fxparsefontdesc. Expected _FXFontDesc_p.");
        return NULL;
        }
    }
    _result = (FXbool )fxparsefontdesc(*_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_fxunparsefontdesc(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXbool  _result;
    FXchar * _arg0;
    FXFontDesc * _arg1;
    PyObject * _argo1 = 0;
    char *_kwnames[] = { "string","fontdesc", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"sO:fxunparsefontdesc",_kwnames,&_arg0,&_argo1)) 
        return NULL;
    if (_argo1) {
        if (_argo1 == Py_None) { _arg1 = NULL; }
        else if (SWIG_GetPtrObj(_argo1,(void **) &_arg1,"_FXFontDesc_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fxunparsefontdesc. Expected _FXFontDesc_p.");
        return NULL;
        }
    }
    _result = (FXbool )fxunparsefontdesc(_arg0,*_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_fxstrhash(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXint  _result;
    FXchar * _arg0;
    char *_kwnames[] = { "str", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"s:fxstrhash",_kwnames,&_arg0)) 
        return NULL;
    _result = (FXint )fxstrhash(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static int _wrap_fxTraceLevel_set(PyObject *val) {
    unsigned int  tval;

    tval = (unsigned int )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'fxTraceLevel'(unsigned int )");
        return 1; 
    }
    fxTraceLevel = tval;
    return 0;
}

static PyObject *_wrap_fxTraceLevel_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) fxTraceLevel);
    return pyobj;
}

static int _wrap_messageTypeNames_set(PyObject *val) {
    PyObject * temp;

    if (val) {
        if (val == Py_None) { temp = NULL; }
        else if (SWIG_GetPtrObj(val,(void **) &temp,"_PyObject_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in value of messageTypeNames. Expected _PyObject_p.");
        return 1;
        }
    }
    messageTypeNames = temp;
    return 0;
}

static PyObject *_wrap_messageTypeNames_get() {
    PyObject * pyobj;

{
  pyobj = messageTypeNames;
}
    return pyobj;
}

static PyObject *_wrap_setErrorObject(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    PyObject * _arg0;
    PyObject * _obj0 = 0;
    char *_kwnames[] = { "errorObject", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"O:setErrorObject",_kwnames,&_obj0)) 
        return NULL;
{
  _arg0 = _obj0;
}
{
    FXPy_BEGIN_ALLOW_THREADS
        setErrorObject(_arg0);

    FXPy_END_ALLOW_THREADS
}    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_MKUINT(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    unsigned int  _result;
    unsigned short  _arg0;
    unsigned short  _arg1;
    char *_kwnames[] = { "l","h", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"hh:MKUINT",_kwnames,&_arg0,&_arg1)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (unsigned int )_MKUINT(_arg0,_arg1);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_SELTYPE(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    unsigned int  _result;
    unsigned int  _arg0;
    char *_kwnames[] = { "arg1", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:SELTYPE",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (unsigned int )_SELTYPE(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_SELID(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    unsigned int  _result;
    unsigned int  _arg0;
    char *_kwnames[] = { "s", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:SELID",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (unsigned int )_SELID(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_FXBITREVERSE(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXuchar  _arg0;
    char *_kwnames[] = { "b", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"b:FXBITREVERSE",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXBITREVERSE(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_FXRGBA(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    unsigned long  _result;
    unsigned int  _arg0;
    unsigned int  _arg1;
    unsigned int  _arg2;
    unsigned int  _arg3;
    char *_kwnames[] = { "r","g","b","a", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"iiii:FXRGBA",_kwnames,&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (unsigned long )_FXRGBA(_arg0,_arg1,_arg2,_arg3);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_FXRGB(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXColor  _result;
    unsigned int  _arg0;
    unsigned int  _arg1;
    unsigned int  _arg2;
    char *_kwnames[] = { "r","g","b", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"iii:FXRGB",_kwnames,&_arg0,&_arg1,&_arg2)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXColor )_FXRGB(_arg0,_arg1,_arg2);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_FXREDVAL(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "rgba", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:FXREDVAL",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXREDVAL(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_FXGREENVAL(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "rgba", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:FXGREENVAL",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXGREENVAL(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_FXBLUEVAL(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "rgba", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:FXBLUEVAL",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXBLUEVAL(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_FXALPHAVAL(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXColor  _arg0;
    char *_kwnames[] = { "rgba", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"i:FXALPHAVAL",_kwnames,&_arg0)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXALPHAVAL(_arg0);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_FXRGBACOMPVAL(PyObject *self, PyObject *args, PyObject *kwargs) {
    PyObject * _resultobj;
    FXuchar  _result;
    FXColor  _arg0;
    FXuchar  _arg1;
    char *_kwnames[] = { "rgba","comp", NULL };

    self = self;
    if(!PyArg_ParseTupleAndKeywords(args,kwargs,"ib:FXRGBACOMPVAL",_kwnames,&_arg0,&_arg1)) 
        return NULL;
{
    FXPy_BEGIN_ALLOW_THREADS
        _result = (FXuchar )_FXRGBACOMPVAL(_arg0,_arg1);

    FXPy_END_ALLOW_THREADS
}    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyMethodDef foxcMethods[] = {
	 { "FXRGBACOMPVAL", (PyCFunction) _wrap_FXRGBACOMPVAL, METH_VARARGS | METH_KEYWORDS },
	 { "FXALPHAVAL", (PyCFunction) _wrap_FXALPHAVAL, METH_VARARGS | METH_KEYWORDS },
	 { "FXBLUEVAL", (PyCFunction) _wrap_FXBLUEVAL, METH_VARARGS | METH_KEYWORDS },
	 { "FXGREENVAL", (PyCFunction) _wrap_FXGREENVAL, METH_VARARGS | METH_KEYWORDS },
	 { "FXREDVAL", (PyCFunction) _wrap_FXREDVAL, METH_VARARGS | METH_KEYWORDS },
	 { "FXRGB", (PyCFunction) _wrap_FXRGB, METH_VARARGS | METH_KEYWORDS },
	 { "FXRGBA", (PyCFunction) _wrap_FXRGBA, METH_VARARGS | METH_KEYWORDS },
	 { "FXBITREVERSE", (PyCFunction) _wrap_FXBITREVERSE, METH_VARARGS | METH_KEYWORDS },
	 { "SELID", (PyCFunction) _wrap_SELID, METH_VARARGS | METH_KEYWORDS },
	 { "SELTYPE", (PyCFunction) _wrap_SELTYPE, METH_VARARGS | METH_KEYWORDS },
	 { "MKUINT", (PyCFunction) _wrap_MKUINT, METH_VARARGS | METH_KEYWORDS },
	 { "setErrorObject", (PyCFunction) _wrap_setErrorObject, METH_VARARGS | METH_KEYWORDS },
	 { "FXPySetDict", (PyCFunction) FXPySetDict, METH_VARARGS | METH_KEYWORDS },
	 { "fxstrhash", (PyCFunction) _wrap_fxstrhash, METH_VARARGS | METH_KEYWORDS },
	 { "fxunparsefontdesc", (PyCFunction) _wrap_fxunparsefontdesc, METH_VARARGS | METH_KEYWORDS },
	 { "fxparsefontdesc", (PyCFunction) _wrap_fxparsefontdesc, METH_VARARGS | METH_KEYWORDS },
	 { "fxhsv_to_rgb", (PyCFunction) _wrap_fxhsv_to_rgb, METH_VARARGS | METH_KEYWORDS },
	 { "fxrgb_to_hsv", (PyCFunction) _wrap_fxrgb_to_hsv, METH_VARARGS | METH_KEYWORDS },
	 { "fxcolorfromname", (PyCFunction) _wrap_fxcolorfromname, METH_VARARGS | METH_KEYWORDS },
	 { "fxgetpid", (PyCFunction) _wrap_fxgetpid, METH_VARARGS | METH_KEYWORDS },
	 { "fxgetpermissions", (PyCFunction) _wrap_fxgetpermissions, METH_VARARGS | METH_KEYWORDS },
	 { "fxgetgroupname", (PyCFunction) _wrap_fxgetgroupname, METH_VARARGS | METH_KEYWORDS },
	 { "fxgetusername", (PyCFunction) _wrap_fxgetusername, METH_VARARGS | METH_KEYWORDS },
	 { "makeShadowColor", (PyCFunction) _wrap_makeShadowColor, METH_VARARGS | METH_KEYWORDS },
	 { "makeHiliteColor", (PyCFunction) _wrap_makeHiliteColor, METH_VARARGS | METH_KEYWORDS },
	 { "fxfindhotkeyoffset", (PyCFunction) _wrap_fxfindhotkeyoffset, METH_VARARGS | METH_KEYWORDS },
	 { "fxparsehotkey", (PyCFunction) _wrap_fxparsehotkey, METH_VARARGS | METH_KEYWORDS },
	 { "fxparseaccel", (PyCFunction) _wrap_fxparseaccel, METH_VARARGS | METH_KEYWORDS },
	 { "fxfilematch", (PyCFunction) _wrap_fxfilematch, METH_VARARGS | METH_KEYWORDS },
	 { "fxsleep", (PyCFunction) _wrap_fxsleep, METH_VARARGS | METH_KEYWORDS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
/*
 * This table is used by the pointer type-checker
 */
static struct { char *n1; char *n2; void *(*pcnv)(void *); } _swig_mapping[] = {
    { "_class_FXPyBMPImage","_FXPyBMPImage",0},
    { "_class_FXPyICOImage","_FXPyICOImage",0},
    { "_FXPyDelegator","_class_FXPyDelegator",0},
    { "_FX4Splitter","_class_FX4Splitter",0},
    { "_class_FXButton","_FXButton",0},
    { "_FXPyRadioButton","_class_FXPyRadioButton",0},
    { "_FXOption","_class_FXOption",0},
    { "_class_FXPyStatusbar","_FXPyStatusbar",0},
    { "_signed_long","_FXTime",0},
    { "_signed_long","_long",0},
    { "_class_FXPyPCXImage","_FXPyPCXImage",0},
    { "_FXBitmap","_class_FXBitmap",0},
    { "_class_FXImageView","_FXImageView",0},
    { "_class_FXPyToolbarTab","_FXPyToolbarTab",0},
    { "_class_FXColorSelector","_FXColorSelector",0},
    { "_FXGLVisual","_class_FXGLVisual",0},
    { "_class_FXGLGroup","_FXGLGroup",0},
    { "_class_FXTIFIcon","_FXTIFIcon",0},
    { "_FXPyHorizontalFrame","_class_FXPyHorizontalFrame",0},
    { "_FXViewport","_struct_FXViewport",0},
    { "_double","_FXdouble",0},
    { "_FXPyObject","_class_FXPyObject",0},
    { "_FXPyGIFIcon","_class_FXPyGIFIcon",0},
    { "_FXBMPIcon","_class_FXBMPIcon",0},
    { "_FXICOIcon","_class_FXICOIcon",0},
    { "_class_FXList","_FXList",0},
    { "_FXTreeItem","_class_FXTreeItem",0},
    { "_FXTablePos","_struct_FXTablePos",0},
    { "_class_FXSettings","_FXSettings",0},
    { "_class_FXRegistry","_FXRegistry",0},
    { "_class_FXMainWindow","_FXMainWindow",0},
    { "_class_FXPyOption","_FXPyOption",0},
    { "_FXTreeList","_class_FXTreeList",0},
    { "_FXDirBox","_class_FXDirBox",0},
    { "_FXFileDict","_class_FXFileDict",0},
    { "_FXPyGLLine","_class_FXPyGLLine",0},
    { "_class_FXPyBitmap","_FXPyBitmap",0},
    { "_FXPySpinner","_class_FXPySpinner",0},
    { "_class_FXColorBar","_FXColorBar",0},
    { "_class_FXPyMenubar","_FXPyMenubar",0},
    { "_FXGLTriangleMesh","_class_FXGLTriangleMesh",0},
    { "_FXTopWindow","_class_FXTopWindow",0},
    { "_FXPySwitcher","_class_FXPySwitcher",0},
    { "_class_FXPyMDIMaximizeButton","_FXPyMDIMaximizeButton",0},
    { "_FXGLCanvas","_class_FXGLCanvas",0},
    { "_FXShutterItem","_class_FXShutterItem",0},
    { "_FXTextField","_class_FXTextField",0},
    { "_class_FXTooltip","_FXTooltip",0},
    { "_FXPyMenuCaption","_class_FXPyMenuCaption",0},
    { "_class_FXPyMDIWindowButton","_FXPyMDIWindowButton",0},
    { "_class_FXVisual","_FXVisual",0},
    { "_FXIcon","_class_FXIcon",0},
    { "_FXPyMatrix","_class_FXPyMatrix",0},
    { "_class_FXStatusbar","_FXStatusbar",0},
    { "_class_FXPyDirBox","_FXPyDirBox",0},
    { "_FXDirSelector","_class_FXDirSelector",0},
    { "_FXDirItem","_class_FXDirItem",0},
    { "_class_FXDCPrint","_FXDCPrint",0},
    { "_class_FXGroupBox","_FXGroupBox",0},
    { "_FXToolbar","_class_FXToolbar",0},
    { "_class_FXPyMDIChild","_FXPyMDIChild",0},
    { "_class_FXIconItem","_FXIconItem",0},
    { "_class_FXGLObject","_FXGLObject",0},
    { "_FXDirList","_class_FXDirList",0},
    { "_FXTGAImage","_class_FXTGAImage",0},
    { "_class_FXPyTGAIcon","_FXPyTGAIcon",0},
    { "_FXPyStream","_class_FXPyStream",0},
    { "_class_FXPyDict","_FXPyDict",0},
    { "_class_FXRegion","_FXRegion",0},
    { "_FXShutter","_class_FXShutter",0},
    { "_class_FXPyToggleButton","_FXPyToggleButton",0},
    { "_class_FXTabBook","_FXTabBook",0},
    { "_class_FXIconList","_FXIconList",0},
    { "_FXPyPNGImage","_class_FXPyPNGImage",0},
    { "_class_FXAccelTable","_FXAccelTable",0},
    { "_class_FXToggleButton","_FXToggleButton",0},
    { "_FXPyApp","_class_FXPyApp",0},
    { "_FXDCWindow","_class_FXDCWindow",0},
    { "_FXPyScrollArea","_class_FXPyScrollArea",0},
    { "_class_FXDragCorner","_FXDragCorner",0},
    { "_class_FXHeader","_FXHeader",0},
    { "_class_FXPyId","_FXPyId",0},
    { "_class_FXCanvas","_FXCanvas",0},
    { "_class_FXPyMenuCascade","_FXPyMenuCascade",0},
    { "_FXPyMenuCommand","_class_FXPyMenuCommand",0},
    { "_FXInputDialog","_class_FXInputDialog",0},
    { "_class_FXPyTableItem","_FXPyTableItem",0},
    { "_FXApp","_class_FXApp",0},
    { "_class_FXPyRecentFiles","_FXPyRecentFiles",0},
    { "_class_FXPyDebugTarget","_FXPyDebugTarget",0},
    { "_class_FXCommand","_FXCommand",0},
    { "_class_FXPyFrame","_FXPyFrame",0},
    { "_FXGIFCursor","_class_FXGIFCursor",0},
    { "_class_FXListItem","_FXListItem",0},
    { "_class_FXTreeListBox","_FXTreeListBox",0},
    { "_struct_FXLight","_FXLight",0},
    { "_FXGLPoint","_class_FXGLPoint",0},
    { "_long","_FXPixel",0},
    { "_long","_FXTime",0},
    { "_long","_unsigned_long",0},
    { "_long","_signed_long",0},
    { "_FXComposite","_class_FXComposite",0},
    { "_struct_FXArc","_FXArc",0},
    { "_class_FXPyMenuButton","_FXPyMenuButton",0},
    { "_class_FXPyFontDialog","_FXPyFontDialog",0},
    { "_FXRGBIcon","_class_FXRGBIcon",0},
    { "_FXScrollArea","_class_FXScrollArea",0},
    { "_FXLabel","_class_FXLabel",0},
    { "_class_FXPyColorWell","_FXPyColorWell",0},
    { "_FXPyMDIDeleteButton","_class_FXPyMDIDeleteButton",0},
    { "_FXPrinter","_struct_FXPrinter",0},
    { "_class_FXId","_FXId",0},
    { "_FXPyHorizontalSeparator","_class_FXPyHorizontalSeparator",0},
    { "_class_FXPyRadioButton","_FXPyRadioButton",0},
    { "_FXProgressBar","_class_FXProgressBar",0},
    { "_FXPyMenuSeparator","_class_FXPyMenuSeparator",0},
    { "_class_FXPyMDIMenu","_FXPyMDIMenu",0},
    { "_FXPrintDialog","_class_FXPrintDialog",0},
    { "_float","_FXfloat",0},
    { "_FXPyDrawable","_class_FXPyDrawable",0},
    { "_class_FXPyXPMIcon","_FXPyXPMIcon",0},
    { "_FXPyScrollWindow","_class_FXPyScrollWindow",0},
    { "_FXPyHeaderItem","_class_FXPyHeaderItem",0},
    { "_FXshort","_short",0},
    { "_FXshort","_signed_short",0},
    { "_FXshort","_unsigned_short",0},
    { "_FXshort","_FXushort",0},
    { "_FXFontDesc","_struct_FXFontDesc",0},
    { "_FXArc","_struct_FXArc",0},
    { "_FXPyIconDict","_class_FXPyIconDict",0},
    { "_FXPyGLCube","_class_FXPyGLCube",0},
    { "_FXSize","_class_FXSize",0},
    { "_class_FXBMPIcon","_FXBMPIcon",0},
    { "_class_FXICOIcon","_FXICOIcon",0},
    { "_FXPyShell","_class_FXPyShell",0},
    { "_class_FXDocument","_FXDocument",0},
    { "_FXPyFileSelector","_class_FXPyFileSelector",0},
    { "_FXPyColorDialog","_class_FXPyColorDialog",0},
    { "_class_FXPyGLGroup","_FXPyGLGroup",0},
    { "_class_FXPyTIFIcon","_FXPyTIFIcon",0},
    { "_FXSegment","_struct_FXSegment",0},
    { "_FXPyButton","_class_FXPyButton",0},
    { "_struct_FXViewport","_FXViewport",0},
    { "_class_FXTableItem","_FXTableItem",0},
    { "_FXHeaderItem","_class_FXHeaderItem",0},
    { "_class_FXMDIWindowButton","_FXMDIWindowButton",0},
    { "_class_FXPyMDIClient","_FXPyMDIClient",0},
    { "_struct_FXTablePos","_FXTablePos",0},
    { "_FXJPGImage","_class_FXJPGImage",0},
    { "_class_FXPySwitcher","_FXPySwitcher",0},
    { "_FXTabBar","_class_FXTabBar",0},
    { "_class_FXTIFImage","_FXTIFImage",0},
    { "_FXPyPCXIcon","_class_FXPyPCXIcon",0},
    { "_FXDC","_class_FXDC",0},
    { "_class_FXColorWell","_FXColorWell",0},
    { "_FXPyArrowButton","_class_FXPyArrowButton",0},
    { "_class_FXPyColorWheel","_FXPyColorWheel",0},
    { "_class_FXPyMenuCaption","_FXPyMenuCaption",0},
    { "_class_FXIcon","_FXIcon",0},
    { "_FXPopup","_class_FXPopup",0},
    { "_FXScrollbar","_class_FXScrollbar",0},
    { "_FXPyDirDialog","_class_FXPyDirDialog",0},
    { "_class_FXDirItem","_FXDirItem",0},
    { "_FXPy4Splitter","_class_FXPy4Splitter",0},
    { "_class_FXPyTooltip","_FXPyTooltip",0},
    { "_FXPyTabItem","_class_FXPyTabItem",0},
    { "_class_FXToolbar","_FXToolbar",0},
    { "_class_FXMenuPane","_FXMenuPane",0},
    { "_class_FXPyMessageBox","_FXPyMessageBox",0},
    { "_class_FXPySearchDialog","_FXPySearchDialog",0},
    { "_FXGLContext","_class_FXGLContext",0},
    { "_FXGLShape","_class_FXGLShape",0},
    { "_class_FXDirList","_FXDirList",0},
    { "_FXHiliteStyle","_struct_FXHiliteStyle",0},
    { "_FXint","_FXInputHandle",0},
    { "_FXint","_FXDragType",0},
    { "_FXint","_FXHotKey",0},
    { "_FXint","_FXColor",0},
    { "_FXint","_FXID",0},
    { "_FXint","_FXSelector",0},
    { "_FXint","_int",0},
    { "_FXint","_signed_int",0},
    { "_FXint","_unsigned_int",0},
    { "_FXint","_FXuint",0},
    { "_FXPyPNGIcon","_class_FXPyPNGIcon",0},
    { "_class_FXWindow","_FXWindow",0},
    { "_FXPyRootWindow","_class_FXPyRootWindow",0},
    { "_class_FXShutter","_FXShutter",0},
    { "_class_FXPyTabBar","_FXPyTabBar",0},
    { "_FXDriveBox","_class_FXDriveBox",0},
    { "_class_FXSearchDialog","_FXSearchDialog",0},
    { "_FXCharset","_class_FXCharset",0},
    { "_FXushort","_FXshort",0},
    { "_FXushort","_unsigned_short",0},
    { "_FXushort","_short",0},
    { "_class_FXPoint","_FXPoint",0},
    { "_class_FXPyPNGImage","_FXPyPNGImage",0},
    { "_class_FXPyDCPrint","_FXPyDCPrint",0},
    { "_FXPyCheckButton","_class_FXPyCheckButton",0},
    { "_class_FXComboBox","_FXComboBox",0},
    { "_FXGLCone","_class_FXGLCone",0},
    { "_FXPyVisual","_class_FXPyVisual",0},
    { "_class_FXPyTabBook","_FXPyTabBook",0},
    { "_FXFileItem","_class_FXFileItem",0},
    { "_class_FXGLViewer","_FXGLViewer",0},
    { "_class_FXRectangle","_FXRectangle",0},
    { "_class_FXPyFont","_FXPyFont",0},
    { "_FXPyFileStream","_class_FXPyFileStream",0},
    { "_class_FXPyStatusline","_FXPyStatusline",0},
    { "_class_FXPyMenuCommand","_FXPyMenuCommand",0},
    { "_class_FXMDIClient","_FXMDIClient",0},
    { "_FXFileList","_class_FXFileList",0},
    { "_FXPyFileDialog","_class_FXPyFileDialog",0},
    { "_FXRGBImage","_class_FXRGBImage",0},
    { "_FXRootWindow","_class_FXRootWindow",0},
    { "_class_FXPacker","_FXPacker",0},
    { "_FXPyToolbarShell","_class_FXPyToolbarShell",0},
    { "_class_FXMDIMaximizeButton","_FXMDIMaximizeButton",0},
    { "_class_FXGLPoint","_FXGLPoint",0},
    { "_FXPyXPMImage","_class_FXPyXPMImage",0},
    { "_FXPyDataTarget","_class_FXPyDataTarget",0},
    { "_FXPyTopWindow","_class_FXPyTopWindow",0},
    { "_FXPyScrollCorner","_class_FXPyScrollCorner",0},
    { "_FXMenuCascade","_class_FXMenuCascade",0},
    { "_FXProgressDialog","_class_FXProgressDialog",0},
    { "_FXGLSphere","_class_FXGLSphere",0},
    { "_class_FXPyGLCone","_FXPyGLCone",0},
    { "_FXObject","_class_FXObject",0},
    { "_FXPyGIFImage","_class_FXPyGIFImage",0},
    { "_FXBMPImage","_class_FXBMPImage",0},
    { "_FXICOImage","_class_FXICOImage",0},
    { "_class_FXRGBIcon","_FXRGBIcon",0},
    { "_FXRecentFiles","_class_FXRecentFiles",0},
    { "_FXDebugTarget","_class_FXDebugTarget",0},
    { "_class_FXPyCommand","_FXPyCommand",0},
    { "_class_FXScrollArea","_FXScrollArea",0},
    { "_FXPySplitter","_class_FXPySplitter",0},
    { "_FXPyTextField","_class_FXPyTextField",0},
    { "_FXPyHeader","_class_FXPyHeader",0},
    { "_FXPCXImage","_class_FXPCXImage",0},
    { "_FXFileStream","_class_FXFileStream",0},
    { "_class_FXPyDelegator","_FXPyDelegator",0},
    { "_FXPyCanvas","_class_FXPyCanvas",0},
    { "_FXFileDialog","_class_FXFileDialog",0},
    { "_FXMaterial","_struct_FXMaterial",0},
    { "_FXGLLine","_class_FXGLLine",0},
    { "_FXPyGLCylinder","_class_FXPyGLCylinder",0},
    { "_class_FXPyDrawable","_FXPyDrawable",0},
    { "_FXPyImage","_class_FXPyImage",0},
    { "_FXGIFIcon","_class_FXGIFIcon",0},
    { "_FXPyDial","_class_FXPyDial",0},
    { "_class_FXPyOptionMenu","_FXPyOptionMenu",0},
    { "_FXPyListBox","_class_FXPyListBox",0},
    { "_class_FXGLVisual","_FXGLVisual",0},
    { "_FXColor","_FXInputHandle",0},
    { "_FXColor","_FXDragType",0},
    { "_FXColor","_FXHotKey",0},
    { "_FXColor","_FXuint",0},
    { "_FXColor","_int",0},
    { "_FXColor","_unsigned_int",0},
    { "_FXColor","_FXint",0},
    { "_FXColor","_FXSelector",0},
    { "_FXColor","_FXID",0},
    { "_FXPyJPGIcon","_class_FXPyJPGIcon",0},
    { "_FXDataTarget","_class_FXDataTarget",0},
    { "_class_FXPyHorizontalFrame","_FXPyHorizontalFrame",0},
    { "_FXRadioButton","_class_FXRadioButton",0},
    { "_class_FXPyList","_FXPyList",0},
    { "_FXMDIRestoreButton","_class_FXMDIRestoreButton",0},
    { "_class_FXPyIconDict","_FXPyIconDict",0},
    { "_FXTime","_FXPixel",0},
    { "_FXTime","_long",0},
    { "_FXTime","_signed_long",0},
    { "_FXTime","_unsigned_long",0},
    { "_FXHotKey","_FXInputHandle",0},
    { "_FXHotKey","_FXDragType",0},
    { "_FXHotKey","_FXuint",0},
    { "_FXHotKey","_int",0},
    { "_FXHotKey","_unsigned_int",0},
    { "_FXHotKey","_FXint",0},
    { "_FXHotKey","_FXSelector",0},
    { "_FXHotKey","_FXID",0},
    { "_FXHotKey","_FXColor",0},
    { "_class_FXSize","_FXSize",0},
    { "_class_FXPyObject","_FXPyObject",0},
    { "_class_FXPyShell","_FXPyShell",0},
    { "_FXPyDC","_class_FXPyDC",0},
    { "_class_FXCursor","_FXCursor",0},
    { "_FXSpinner","_class_FXSpinner",0},
    { "_class_FXPyMDIRestoreButton","_FXPyMDIRestoreButton",0},
    { "_class_FXTreeItem","_FXTreeItem",0},
    { "_class_FXPyColorDialog","_FXPyColorDialog",0},
    { "_struct_FXFontDesc","_FXFontDesc",0},
    { "_FXMatrix","_class_FXMatrix",0},
    { "_class_FXTreeList","_FXTreeList",0},
    { "_class_FXFileDict","_FXFileDict",0},
    { "_class_FXPyGLLine","_FXPyGLLine",0},
    { "_FXGLCylinder","_class_FXGLCylinder",0},
    { "_FXPyTable","_class_FXPyTable",0},
    { "_class_FXPyBMPIcon","_FXPyBMPIcon",0},
    { "_class_FXPyICOIcon","_FXPyICOIcon",0},
    { "_class_FXHeaderItem","_FXHeaderItem",0},
    { "_class_FXGLTriangleMesh","_FXGLTriangleMesh",0},
    { "_char","_FXchar",0},
    { "_FXdouble","_double",0},
    { "_FXStream","_class_FXStream",0},
    { "_FXPyStringDict","_class_FXPyStringDict",0},
    { "_FXFrame","_class_FXFrame",0},
    { "_FXPyGIFCursor","_class_FXPyGIFCursor",0},
    { "_class_FXPicker","_FXPicker",0},
    { "_FXPyToolbarGrip","_class_FXPyToolbarGrip",0},
    { "_FXPyColorBar","_class_FXPyColorBar",0},
    { "_class_FXGLCanvas","_FXGLCanvas",0},
    { "_FXObjectPtr","_FXObject_p",0},
    { "_FXPyComposite","_class_FXPyComposite",0},
    { "_class_FXShutterItem","_FXShutterItem",0},
    { "_class_FXPyArrowButton","_FXPyArrowButton",0},
    { "_class_FXDelegator","_FXDelegator",0},
    { "_FXVerticalFrame","_class_FXVerticalFrame",0},
    { "_class_FXPyMatrix","_FXPyMatrix",0},
    { "_FXMDIChild","_class_FXMDIChild",0},
    { "_class_FXDirSelector","_FXDirSelector",0},
    { "_class_FXSlider","_FXSlider",0},
    { "_FXMenuCaption","_class_FXMenuCaption",0},
    { "_FXPyColorSelector","_class_FXPyColorSelector",0},
    { "_class_FXGLShape","_FXGLShape",0},
    { "_FXbool","_FXuchar",0},
    { "_FXbool","_unsigned_char",0},
    { "_class_FXTGAImage","_FXTGAImage",0},
    { "_class_FXPyStream","_FXPyStream",0},
    { "_FXStringDict","_class_FXStringDict",0},
    { "_FXPyGroupBox","_class_FXPyGroupBox",0},
    { "_FXPyIconItem","_class_FXPyIconItem",0},
    { "_FXDialogBox","_class_FXDialogBox",0},
    { "_FXPyGLObject","_class_FXPyGLObject",0},
    { "_class_FXPyDirItem","_FXPyDirItem",0},
    { "_class_FXCharset","_FXCharset",0},
    { "_class_FXPyCheckButton","_FXPyCheckButton",0},
    { "_class_FXPyToolbar","_FXPyToolbar",0},
    { "_FXPyIconList","_class_FXPyIconList",0},
    { "_class_FXPyDirList","_FXPyDirList",0},
    { "_class_FXPyApp","_FXPyApp",0},
    { "_class_FXDCWindow","_FXDCWindow",0},
    { "_class_FXPyShutter","_FXPyShutter",0},
    { "_FXFontSelector","_class_FXFontSelector",0},
    { "_class_FXInputDialog","_FXInputDialog",0},
    { "_FXPyText","_class_FXPyText",0},
    { "_FXPyWindow","_class_FXPyWindow",0},
    { "_class_FXRootWindow","_FXRootWindow",0},
    { "_FXCURCursor","_class_FXCURCursor",0},
    { "_FXMenuTitle","_class_FXMenuTitle",0},
    { "_class_FXPyXPMImage","_FXPyXPMImage",0},
    { "_FXPyListItem","_class_FXPyListItem",0},
    { "_FXMenuCommand","_class_FXMenuCommand",0},
    { "_FXGLCube","_class_FXGLCube",0},
    { "_class_FXPyGIFImage","_FXPyGIFImage",0},
    { "_class_FXPyVerticalFrame","_FXPyVerticalFrame",0},
    { "_class_FXPySplitter","_FXPySplitter",0},
    { "_class_FXLabel","_FXLabel",0},
    { "_class_FXPyMDIDeleteButton","_FXPyMDIDeleteButton",0},
    { "_class_FXPyGLPoint","_FXPyGLPoint",0},
    { "_class_FXFileStream","_FXFileStream",0},
    { "_class_FXPyMainWindow","_FXPyMainWindow",0},
    { "_class_FXHorizontalFrame","_FXHorizontalFrame",0},
    { "_FXButton","_class_FXButton",0},
    { "_FXPyScrollbar","_class_FXPyScrollbar",0},
    { "_class_FXProgressBar","_FXProgressBar",0},
    { "_class_FXFileDialog","_FXFileDialog",0},
    { "_class_FXPrintDialog","_FXPrintDialog",0},
    { "_class_FXPyImage","_FXPyImage",0},
    { "_class_FXGIFIcon","_FXGIFIcon",0},
    { "_class_FXPyRGBIcon","_FXPyRGBIcon",0},
    { "_FXPyPacker","_class_FXPyPacker",0},
    { "_class_FXPyScrollWindow","_FXPyScrollWindow",0},
    { "_FXImageView","_class_FXImageView",0},
    { "_FXPyToolbarTab","_class_FXPyToolbarTab",0},
    { "_FXPyGLContext","_class_FXPyGLContext",0},
    { "_unsigned_long","_FXPixel",0},
    { "_unsigned_long","_FXTime",0},
    { "_unsigned_long","_long",0},
    { "_class_FXDataTarget","_FXDataTarget",0},
    { "_class_FXScrollWindow","_FXScrollWindow",0},
    { "_FXDial","_class_FXDial",0},
    { "_class_FXMDIRestoreButton","_FXMDIRestoreButton",0},
    { "_FXReplaceDialog","_class_FXReplaceDialog",0},
    { "_struct_FXMaterial","_FXMaterial",0},
    { "_class_FXPyGLCube","_FXPyGLCube",0},
    { "_class_FXPyDC","_FXPyDC",0},
    { "_FXPyVerticalSeparator","_class_FXPyVerticalSeparator",0},
    { "_class_FXSpinner","_FXSpinner",0},
    { "_class_FXPyFileSelector","_FXPyFileSelector",0},
    { "_class_FXPyButton","_FXPyButton",0},
    { "_FXPyDocument","_class_FXPyDocument",0},
    { "_class_FXFileSelector","_FXFileSelector",0},
    { "_class_FXGLCylinder","_FXGLCylinder",0},
    { "_class_FXPyTable","_FXPyTable",0},
    { "_FXPCXIcon","_class_FXPCXIcon",0},
    { "_FXSwitcher","_class_FXSwitcher",0},
    { "_FXToolbarTab","_class_FXToolbarTab",0},
    { "_FXPyMenubar","_class_FXPyMenubar",0},
    { "_FXColorDialog","_class_FXColorDialog",0},
    { "_class_FXJPGImage","_FXJPGImage",0},
    { "_class_FXPyToolbarGrip","_FXPyToolbarGrip",0},
    { "_class_FXPyColorBar","_FXPyColorBar",0},
    { "_class_FXPyIcon","_FXPyIcon",0},
    { "_class_FXPyAccelTable","_FXPyAccelTable",0},
    { "_class_FXDC","_FXDC",0},
    { "_FXPyCursor","_class_FXPyCursor",0},
    { "_FXTabItem","_class_FXTabItem",0},
    { "_FXVisual","_class_FXVisual",0},
    { "_FXPyTIFImage","_class_FXPyTIFImage",0},
    { "_FXPNGIcon","_class_FXPNGIcon",0},
    { "_class_FXPopup","_FXPopup",0},
    { "_class_FXVerticalFrame","_FXVerticalFrame",0},
    { "_class_FXPyDragCorner","_FXPyDragCorner",0},
    { "_FXStatusbar","_class_FXStatusbar",0},
    { "_class_FXPyDirDialog","_FXPyDirDialog",0},
    { "_signed_int","_FXInputHandle",0},
    { "_signed_int","_FXint",0},
    { "_signed_int","_int",0},
    { "_class_FXPy4Splitter","_FXPy4Splitter",0},
    { "_FXArrowButton","_class_FXArrowButton",0},
    { "_FXFileAssoc","_struct_FXFileAssoc",0},
    { "_FXPyGLTriangleMesh","_class_FXPyGLTriangleMesh",0},
    { "_FXPNGImage","_class_FXPNGImage",0},
    { "_FXPyTGAIcon","_class_FXPyTGAIcon",0},
    { "_FXPyDict","_class_FXPyDict",0},
    { "_class_FXStringDict","_FXStringDict",0},
    { "_FXRegion","_class_FXRegion",0},
    { "_class_FXPyGroupBox","_FXPyGroupBox",0},
    { "_FXPyPicker","_class_FXPyPicker",0},
    { "_class_FXDriveBox","_FXDriveBox",0},
    { "_FXPyMenuPane","_class_FXPyMenuPane",0},
    { "_class_FXPyIconItem","_FXPyIconItem",0},
    { "_class_FXPyReplaceDialog","_FXPyReplaceDialog",0},
    { "_class_FXPyGLObject","_FXPyGLObject",0},
    { "_FXVerticalSeparator","_class_FXVerticalSeparator",0},
    { "_FXToggleButton","_class_FXToggleButton",0},
    { "_class_FXPyIconList","_FXPyIconList",0},
    { "_class_FXPyGLShape","_FXPyGLShape",0},
    { "_FXRawEvent","__XEvent",0},
    { "_class_FXPyVisual","_FXPyVisual",0},
    { "_FXShell","_class_FXShell",0},
    { "_FXPyComboBox","_class_FXPyComboBox",0},
    { "_FXHeader","_class_FXHeader",0},
    { "_FXPyTreeListBox","_class_FXPyTreeListBox",0},
    { "_class_FXFileItem","_FXFileItem",0},
    { "_FXCanvas","_class_FXCanvas",0},
    { "_FXCheckButton","_class_FXCheckButton",0},
    { "_FXPySlider","_class_FXPySlider",0},
    { "_class_FXFileList","_FXFileList",0},
    { "_FXPyGLViewer","_class_FXPyGLViewer",0},
    { "_class_FXRGBImage","_FXRGBImage",0},
    { "_class_FXPyToolbarShell","_FXPyToolbarShell",0},
    { "_class_FXMDIDeleteButton","_FXMDIDeleteButton",0},
    { "_FXText","_class_FXText",0},
    { "_unsigned_short","_FXshort",0},
    { "_unsigned_short","_FXushort",0},
    { "_unsigned_short","_short",0},
    { "_class_FXPyTopWindow","_FXPyTopWindow",0},
    { "_class_FXPyScrollCorner","_FXPyScrollCorner",0},
    { "_class_FXPyListItem","_FXPyListItem",0},
    { "_class_FXToolbarShell","_FXToolbarShell",0},
    { "_FXPyMenuButton","_class_FXPyMenuButton",0},
    { "_class_FXMenuCascade","_FXMenuCascade",0},
    { "_FXPyFontDialog","_class_FXPyFontDialog",0},
    { "_class_FXProgressDialog","_FXProgressDialog",0},
    { "_class_FXGLSphere","_FXGLSphere",0},
    { "_class_FXBMPImage","_FXBMPImage",0},
    { "_class_FXICOImage","_FXICOImage",0},
    { "_class_FXRecentFiles","_FXRecentFiles",0},
    { "_class_FXDebugTarget","_FXDebugTarget",0},
    { "_class_FXPyTextField","_FXPyTextField",0},
    { "_class_FXScrollCorner","_FXScrollCorner",0},
    { "_class_FXPyHeader","_FXPyHeader",0},
    { "_FXListBox","_class_FXListBox",0},
    { "_class_FXDirDialog","_FXDirDialog",0},
    { "_FXDrawable","_class_FXDrawable",0},
    { "_class_FXPCXImage","_FXPCXImage",0},
    { "_FXJPGIcon","_class_FXJPGIcon",0},
    { "_class_FXPyCanvas","_FXPyCanvas",0},
    { "_class_FX4Splitter","_FX4Splitter",0},
    { "_class_FXOption","_FXOption",0},
    { "_FXPyMDIMenu","_class_FXPyMDIMenu",0},
    { "_FXPyXPMIcon","_class_FXPyXPMIcon",0},
    { "_class_FXBitmap","_FXBitmap",0},
    { "_FXPyMDIMinimizeButton","_class_FXPyMDIMinimizeButton",0},
    { "_FXIconDict","_class_FXIconDict",0},
    { "_FXObject_p","_FXObjectPtr",0},
    { "_FXID","_FXInputHandle",0},
    { "_FXID","_FXDragType",0},
    { "_FXID","_FXHotKey",0},
    { "_FXID","_FXColor",0},
    { "_FXID","_unsigned_int",0},
    { "_FXID","_int",0},
    { "_FXID","_FXuint",0},
    { "_FXID","_FXint",0},
    { "_FXID","_FXSelector",0},
    { "_FXHorizontalSeparator","_class_FXHorizontalSeparator",0},
    { "_class_FXDial","_FXDial",0},
    { "_class_FXRadioButton","_FXRadioButton",0},
    { "_FXMenuButton","_class_FXMenuButton",0},
    { "_FXPyDialogBox","_class_FXPyDialogBox",0},
    { "_FXFontDialog","_class_FXFontDialog",0},
    { "_class_FXReplaceDialog","_FXReplaceDialog",0},
    { "_FXPyGLVisual","_class_FXPyGLVisual",0},
    { "_class_FXPyGIFIcon","_FXPyGIFIcon",0},
    { "_class_FXPyVerticalSeparator","_FXPyVerticalSeparator",0},
    { "_FXPyGLGroup","_class_FXPyGLGroup",0},
    { "_struct_FXPrinter","_FXPrinter",0},
    { "_FXPyTIFIcon","_class_FXPyTIFIcon",0},
    { "_class_FXPyDocument","_FXPyDocument",0},
    { "_FXPyTreeItem","_class_FXPyTreeItem",0},
    { "_class_FXDirBox","_FXDirBox",0},
    { "_FXTableItem","_class_FXTableItem",0},
    { "_class_FXPCXIcon","_FXPCXIcon",0},
    { "_class_FXPySpinner","_FXPySpinner",0},
    { "_class_FXToolbarTab","_FXToolbarTab",0},
    { "_FXMDIWindowButton","_class_FXMDIWindowButton",0},
    { "_FXPyTreeList","_class_FXPyTreeList",0},
    { "_FXPyFileDict","_class_FXPyFileDict",0},
    { "_struct_FXHiliteStyle","_FXHiliteStyle",0},
    { "_signed_short","_FXshort",0},
    { "_signed_short","_short",0},
    { "_class_FXFrame","_FXFrame",0},
    { "_class_FXTopWindow","_FXTopWindow",0},
    { "_class_FXPyGIFCursor","_FXPyGIFCursor",0},
    { "_FXPyCURCursor","_class_FXPyCURCursor",0},
    { "_FXPyMenuTitle","_class_FXPyMenuTitle",0},
    { "_FXfloat","_float",0},
    { "_FXEvent","_struct_FXEvent",0},
    { "_class_FXPyComposite","_FXPyComposite",0},
    { "_FXColorWell","_class_FXColorWell",0},
    { "_class_FXTextField","_FXTextField",0},
    { "_class_FXTabItem","_FXTabItem",0},
    { "_FXPyColorWheel","_class_FXPyColorWheel",0},
    { "_FXPyGLCanvas","_class_FXPyGLCanvas",0},
    { "_class_FXPyTIFImage","_FXPyTIFImage",0},
    { "_class_FXPNGIcon","_FXPNGIcon",0},
    { "_struct_FXSegment","_FXSegment",0},
    { "_FXToolbarGrip","_class_FXToolbarGrip",0},
    { "_class_FXMDIChild","_FXMDIChild",0},
    { "_FXPyTooltip","_class_FXPyTooltip",0},
    { "_FXMenuSeparator","_class_FXMenuSeparator",0},
    { "_class_FXMenuCaption","_FXMenuCaption",0},
    { "_FXMDIMinimizeButton","_class_FXMDIMinimizeButton",0},
    { "_FXPyMessageBox","_class_FXPyMessageBox",0},
    { "_class_FXPyGLTriangleMesh","_FXPyGLTriangleMesh",0},
    { "_unsigned_char","_FXbool",0},
    { "_unsigned_char","_FXuchar",0},
    { "_FXPixel","_unsigned_long",0},
    { "_FXPixel","_long",0},
    { "_FXPixel","_FXTime",0},
    { "_FXImage","_class_FXImage",0},
    { "_FXWindow","_class_FXWindow",0},
    { "_FXPyImageView","_class_FXPyImageView",0},
    { "_class_FXPyMenuPane","_FXPyMenuPane",0},
    { "_FXSearchDialog","_class_FXSearchDialog",0},
    { "_unsigned_int","_FXInputHandle",0},
    { "_unsigned_int","_FXDragType",0},
    { "_unsigned_int","_FXHotKey",0},
    { "_unsigned_int","_FXColor",0},
    { "_unsigned_int","_FXID",0},
    { "_unsigned_int","_FXSelector",0},
    { "_unsigned_int","_FXint",0},
    { "_unsigned_int","_FXuint",0},
    { "_unsigned_int","_int",0},
    { "_FXPyTGAImage","_class_FXPyTGAImage",0},
    { "_FXDict","_class_FXDict",0},
    { "_FXPyDCPrint","_class_FXPyDCPrint",0},
    { "_FXColorWheel","_class_FXColorWheel",0},
    { "_FXuint","_FXInputHandle",0},
    { "_FXuint","_FXDragType",0},
    { "_FXuint","_FXHotKey",0},
    { "_FXuint","_FXColor",0},
    { "_FXuint","_FXID",0},
    { "_FXuint","_FXSelector",0},
    { "_FXuint","_FXint",0},
    { "_FXuint","_unsigned_int",0},
    { "_FXuint","_int",0},
    { "_class_FXPyScrollArea","_FXPyScrollArea",0},
    { "_FXPyTabBook","_class_FXPyTabBook",0},
    { "_class_FXPyComboBox","_FXPyComboBox",0},
    { "_class_FXPyTreeListBox","_FXPyTreeListBox",0},
    { "_FXPyFontSelector","_class_FXPyFontSelector",0},
    { "_short","_FXshort",0},
    { "_short","_FXushort",0},
    { "_short","_unsigned_short",0},
    { "_short","_signed_short",0},
    { "_FXRectangle","_class_FXRectangle",0},
    { "_FXPyFont","_class_FXPyFont",0},
    { "_FXPyDCWindow","_class_FXPyDCWindow",0},
    { "_FXPyStatusline","_class_FXPyStatusline",0},
    { "_FXMDIClient","_class_FXMDIClient",0},
    { "_FXMessageBox","_class_FXMessageBox",0},
    { "_class_FXPyGLViewer","_FXPyGLViewer",0},
    { "_FXTable","_class_FXTable",0},
    { "_class_FXApp","_FXApp",0},
    { "_FXXPMImage","_class_FXXPMImage",0},
    { "_class_FXPyWindow","_FXPyWindow",0},
    { "_FXPacker","_class_FXPacker",0},
    { "_class_FXGIFCursor","_FXGIFCursor",0},
    { "_class_FXText","_FXText",0},
    { "_FXGIFImage","_class_FXGIFImage",0},
    { "_class_FXComposite","_FXComposite",0},
    { "_FXSplitter","_class_FXSplitter",0},
    { "_class_FXMenuCommand","_FXMenuCommand",0},
    { "_FXPyCommand","_class_FXPyCommand",0},
    { "_class_FXListBox","_FXListBox",0},
    { "_class_FXJPGIcon","_FXJPGIcon",0},
    { "_class_FXPyHorizontalSeparator","_FXPyHorizontalSeparator",0},
    { "_class_FXPyScrollbar","_FXPyScrollbar",0},
    { "_FXStatusline","_class_FXStatusline",0},
    { "_FXPyStatusbar","_class_FXPyStatusbar",0},
    { "_class_FXPyMenuSeparator","_FXPyMenuSeparator",0},
    { "_struct_FXTableRange","_FXTableRange",0},
    { "_FXchar","_char",0},
    { "_class_FXPyPacker","_FXPyPacker",0},
    { "_FXPyOptionMenu","_class_FXPyOptionMenu",0},
    { "_class_FXPyHeaderItem","_FXPyHeaderItem",0},
    { "_class_FXPyMDIMinimizeButton","_FXPyMDIMinimizeButton",0},
    { "_class_FXPyGLContext","_FXPyGLContext",0},
    { "_FXuchar","_FXbool",0},
    { "_FXuchar","_unsigned_char",0},
    { "_class_FXHorizontalSeparator","_FXHorizontalSeparator",0},
    { "_FXPyList","_class_FXPyList",0},
    { "_class_FXMenuButton","_FXMenuButton",0},
    { "_class_FXFontDialog","_FXFontDialog",0},
    { "_FXPyProgressDialog","_class_FXPyProgressDialog",0},
    { "_class_FXPyGLVisual","_FXPyGLVisual",0},
    { "_int","_FXInputHandle",0},
    { "_int","_FXDragType",0},
    { "_int","_FXHotKey",0},
    { "_int","_FXColor",0},
    { "_int","_FXID",0},
    { "_int","_FXSelector",0},
    { "_int","_FXint",0},
    { "_int","_FXuint",0},
    { "_int","_unsigned_int",0},
    { "_int","_signed_int",0},
    { "_FXDragType","_FXInputHandle",0},
    { "_FXDragType","_FXID",0},
    { "_FXDragType","_FXSelector",0},
    { "_FXDragType","_FXint",0},
    { "_FXDragType","_FXuint",0},
    { "_FXDragType","_int",0},
    { "_FXDragType","_unsigned_int",0},
    { "_FXDragType","_FXColor",0},
    { "_FXDragType","_FXHotKey",0},
    { "_FXCursor","_class_FXCursor",0},
    { "_FXMenubar","_class_FXMenubar",0},
    { "_FXPyMDIRestoreButton","_class_FXPyMDIRestoreButton",0},
    { "_FXSettings","_class_FXSettings",0},
    { "_FXRegistry","_class_FXRegistry",0},
    { "_FXPyOption","_class_FXPyOption",0},
    { "_class_FXPyTreeItem","_FXPyTreeItem",0},
    { "_FXPyBMPIcon","_class_FXPyBMPIcon",0},
    { "_FXPyICOIcon","_class_FXPyICOIcon",0},
    { "_class_FXSwitcher","_FXSwitcher",0},
    { "_FXPyShutterItem","_class_FXPyShutterItem",0},
    { "_FXPyBitmap","_class_FXPyBitmap",0},
    { "_FXOptionMenu","_class_FXOptionMenu",0},
    { "_FXColorBar","_class_FXColorBar",0},
    { "_class_FXPyTreeList","_FXPyTreeList",0},
    { "_class_FXColorDialog","_FXColorDialog",0},
    { "_class_FXPyFileDict","_FXPyFileDict",0},
    { "_FXPicker","_class_FXPicker",0},
    { "_class_FXTabBar","_FXTabBar",0},
    { "_FXPyDirSelector","_class_FXPyDirSelector",0},
    { "_FXPSBounds","_struct_FXPSBounds",0},
    { "_FXPyJPGImage","_class_FXPyJPGImage",0},
    { "_class_FXPyPCXIcon","_FXPyPCXIcon",0},
    { "_class_FXPyCursor","_FXPyCursor",0},
    { "_FXPyLabel","_class_FXPyLabel",0},
    { "_FXPyMDIWindowButton","_class_FXPyMDIWindowButton",0},
    { "_class_FXPyGLCanvas","_FXPyGLCanvas",0},
    { "_FXTGAIcon","_class_FXTGAIcon",0},
    { "_FXDelegator","_class_FXDelegator",0},
    { "_class_FXScrollbar","_FXScrollbar",0},
    { "_FXPyDirBox","_class_FXPyDirBox",0},
    { "_FXTableRange","_struct_FXTableRange",0},
    { "_FXGroupBox","_class_FXGroupBox",0},
    { "_class_FXArrowButton","_FXArrowButton",0},
    { "_class_FXPyTabItem","_FXPyTabItem",0},
    { "_FXSlider","_class_FXSlider",0},
    { "_class_FXMenuSeparator","_FXMenuSeparator",0},
    { "_FXIconItem","_class_FXIconItem",0},
    { "_class_FXGLContext","_FXGLContext",0},
    { "_FXGLObject","_class_FXGLObject",0},
    { "_class_FXPNGImage","_FXPNGImage",0},
    { "_class_FXPyPNGIcon","_FXPyPNGIcon",0},
    { "_class_FXPyRootWindow","_FXPyRootWindow",0},
    { "_FXPyToggleButton","_class_FXPyToggleButton",0},
    { "_class_FXPyPicker","_FXPyPicker",0},
    { "_FXIconList","_class_FXIconList",0},
    { "_FXPyDirItem","_class_FXPyDirItem",0},
    { "_class_FXPyTGAImage","_FXPyTGAImage",0},
    { "_class_FXDict","_FXDict",0},
    { "_class_FXVerticalSeparator","_FXVerticalSeparator",0},
    { "_FXPyToolbar","_class_FXPyToolbar",0},
    { "_FXPyDriveBox","_class_FXPyDriveBox",0},
    { "_class_FXColorWheel","_FXColorWheel",0},
    { "_FXPyInputDialog","_class_FXPyInputDialog",0},
    { "_class_FXGLCone","_FXGLCone",0},
    { "_FXPyDirList","_class_FXPyDirList",0},
    { "_class_FXShell","_FXShell",0},
    { "_FXPyShutter","_class_FXPyShutter",0},
    { "_FXInputHandle","_FXint",0},
    { "_FXInputHandle","_FXuint",0},
    { "_FXInputHandle","_unsigned_int",0},
    { "_FXInputHandle","_signed_int",0},
    { "_FXInputHandle","_int",0},
    { "_FXInputHandle","_FXSelector",0},
    { "_FXInputHandle","_FXID",0},
    { "_FXInputHandle","_FXColor",0},
    { "_FXInputHandle","_FXHotKey",0},
    { "_FXInputHandle","_FXDragType",0},
    { "_class_FXPyFileStream","_FXPyFileStream",0},
    { "_class_FXPyDCWindow","_FXPyDCWindow",0},
    { "_class_FXCheckButton","_FXCheckButton",0},
    { "_class_FXPySlider","_FXPySlider",0},
    { "_FXPyFileItem","_class_FXPyFileItem",0},
    { "_class_FXPyFileDialog","_FXPyFileDialog",0},
    { "_class_FXMessageBox","_FXMessageBox",0},
    { "_FXPyTableItem","_class_FXPyTableItem",0},
    { "_FXFont","_class_FXFont",0},
    { "_FXListItem","_class_FXListItem",0},
    { "_FXTreeListBox","_class_FXTreeListBox",0},
    { "_FXPyFileList","_class_FXPyFileList",0},
    { "_FXPyRGBImage","_class_FXPyRGBImage",0},
    { "_class_FXPyDataTarget","_FXPyDataTarget",0},
    { "_FXPyProgressBar","_class_FXPyProgressBar",0},
    { "_FXMDIMenu","_class_FXMDIMenu",0},
    { "_FXPyPrintDialog","_class_FXPyPrintDialog",0},
    { "_FXLight","_struct_FXLight",0},
    { "_class_FXObject","_FXObject",0},
    { "_FXXPMIcon","_class_FXXPMIcon",0},
    { "_FXPyPopup","_class_FXPyPopup",0},
    { "_FXPyVerticalFrame","_class_FXPyVerticalFrame",0},
    { "_FXPyColorWell","_class_FXPyColorWell",0},
    { "_FXPyGLPoint","_class_FXPyGLPoint",0},
    { "_FXPyGLSphere","_class_FXPyGLSphere",0},
    { "_FXId","_class_FXId",0},
    { "_class_FXDrawable","_FXDrawable",0},
    { "_FXPyBMPImage","_class_FXPyBMPImage",0},
    { "_FXPyICOImage","_class_FXPyICOImage",0},
    { "_FXPyMainWindow","_class_FXPyMainWindow",0},
    { "_FXHorizontalFrame","_class_FXHorizontalFrame",0},
    { "_class_FXStatusline","_FXStatusline",0},
    { "_class_FXGLLine","_FXGLLine",0},
    { "_class_FXPyGLCylinder","_FXPyGLCylinder",0},
    { "_FXPyPCXImage","_class_FXPyPCXImage",0},
    { "_FXPyRGBIcon","_class_FXPyRGBIcon",0},
    { "_class_FXPyDial","_FXPyDial",0},
    { "_class_FXPyListBox","_FXPyListBox",0},
    { "_FXColorSelector","_class_FXColorSelector",0},
    { "_class_FXIconDict","_FXIconDict",0},
    { "_FXGLGroup","_class_FXGLGroup",0},
    { "_class_FXPyJPGIcon","_FXPyJPGIcon",0},
    { "_FXTIFIcon","_class_FXTIFIcon",0},
    { "_FXScrollWindow","_class_FXScrollWindow",0},
    { "_class_FXPyDialogBox","_FXPyDialogBox",0},
    { "_class_FXPyProgressDialog","_FXPyProgressDialog",0},
    { "_FXList","_class_FXList",0},
    { "_class_FXMenubar","_FXMenubar",0},
    { "_FXDocument","_class_FXDocument",0},
    { "_FXMainWindow","_class_FXMainWindow",0},
    { "_class_FXMatrix","_FXMatrix",0},
    { "_FXFileSelector","_class_FXFileSelector",0},
    { "__XEvent","_FXRawEvent",0},
    { "_class_FXPyShutterItem","_FXPyShutterItem",0},
    { "_class_FXOptionMenu","_FXOptionMenu",0},
    { "_FXPyMDIClient","_class_FXPyMDIClient",0},
    { "_struct_FXEvent","_FXEvent",0},
    { "_class_FXStream","_FXStream",0},
    { "_class_FXPyStringDict","_FXPyStringDict",0},
    { "_class_FXPyCURCursor","_FXPyCURCursor",0},
    { "_class_FXPyMenuTitle","_FXPyMenuTitle",0},
    { "_FXPyMDIMaximizeButton","_class_FXPyMDIMaximizeButton",0},
    { "_class_FXPyDirSelector","_FXPyDirSelector",0},
    { "_class_FXPyJPGImage","_FXPyJPGImage",0},
    { "_FXTIFImage","_class_FXTIFImage",0},
    { "_FXPyIcon","_class_FXPyIcon",0},
    { "_FXPyAccelTable","_class_FXPyAccelTable",0},
    { "_class_FXPyLabel","_FXPyLabel",0},
    { "_FXTooltip","_class_FXTooltip",0},
    { "_class_FXTGAIcon","_FXTGAIcon",0},
    { "_FXPyDragCorner","_class_FXPyDragCorner",0},
    { "_class_FXToolbarGrip","_FXToolbarGrip",0},
    { "_struct_FXPSBounds","_FXPSBounds",0},
    { "_FXDCPrint","_class_FXDCPrint",0},
    { "_FXMenuPane","_class_FXMenuPane",0},
    { "_class_FXMDIMinimizeButton","_FXMDIMinimizeButton",0},
    { "_FXPyMDIChild","_class_FXPyMDIChild",0},
    { "_class_FXPyColorSelector","_FXPyColorSelector",0},
    { "_FXPySearchDialog","_class_FXPySearchDialog",0},
    { "_class_FXImage","_FXImage",0},
    { "_class_FXPyImageView","_FXPyImageView",0},
    { "_FXPyTabBar","_class_FXPyTabBar",0},
    { "_FXTabBook","_class_FXTabBook",0},
    { "_class_FXDialogBox","_FXDialogBox",0},
    { "_struct_FXFileAssoc","_FXFileAssoc",0},
    { "_FXPyReplaceDialog","_class_FXPyReplaceDialog",0},
    { "_FXPoint","_class_FXPoint",0},
    { "_FXAccelTable","_class_FXAccelTable",0},
    { "_FXComboBox","_class_FXComboBox",0},
    { "_class_FXPyDriveBox","_FXPyDriveBox",0},
    { "_class_FXPyInputDialog","_FXPyInputDialog",0},
    { "_FXPyGLShape","_class_FXPyGLShape",0},
    { "_FXDragCorner","_class_FXDragCorner",0},
    { "_class_FXPyFontSelector","_FXPyFontSelector",0},
    { "_FXGLViewer","_class_FXGLViewer",0},
    { "_FXPyId","_class_FXPyId",0},
    { "_FXPyMenuCascade","_class_FXPyMenuCascade",0},
    { "_class_FXPyFileItem","_FXPyFileItem",0},
    { "_class_FXFontSelector","_FXFontSelector",0},
    { "_class_FXTable","_FXTable",0},
    { "_class_FXPyText","_FXPyText",0},
    { "_FXSelector","_FXInputHandle",0},
    { "_FXSelector","_FXDragType",0},
    { "_FXSelector","_FXHotKey",0},
    { "_FXSelector","_FXColor",0},
    { "_FXSelector","_FXID",0},
    { "_FXSelector","_FXuint",0},
    { "_FXSelector","_int",0},
    { "_FXSelector","_unsigned_int",0},
    { "_FXSelector","_FXint",0},
    { "_class_FXFont","_FXFont",0},
    { "_class_FXXPMImage","_FXXPMImage",0},
    { "_FXPyRecentFiles","_class_FXPyRecentFiles",0},
    { "_FXPyDebugTarget","_class_FXPyDebugTarget",0},
    { "_FXCommand","_class_FXCommand",0},
    { "_FXPyFrame","_class_FXPyFrame",0},
    { "_class_FXCURCursor","_FXCURCursor",0},
    { "_class_FXMenuTitle","_FXMenuTitle",0},
    { "_FXMDIDeleteButton","_class_FXMDIDeleteButton",0},
    { "_FXMDIMaximizeButton","_class_FXMDIMaximizeButton",0},
    { "_class_FXPyFileList","_FXPyFileList",0},
    { "_class_FXGIFImage","_FXGIFImage",0},
    { "_class_FXPyRGBImage","_FXPyRGBImage",0},
    { "_class_FXSplitter","_FXSplitter",0},
    { "_class_FXPyProgressBar","_FXPyProgressBar",0},
    { "_FXToolbarShell","_class_FXToolbarShell",0},
    { "_class_FXMDIMenu","_FXMDIMenu",0},
    { "_class_FXPyPrintDialog","_FXPyPrintDialog",0},
    { "_class_FXGLCube","_FXGLCube",0},
    { "_FXPyGLCone","_class_FXPyGLCone",0},
    { "_class_FXXPMIcon","_FXXPMIcon",0},
    { "_class_FXPyPopup","_FXPyPopup",0},
    { "_FXScrollCorner","_class_FXScrollCorner",0},
    { "_FXDirDialog","_class_FXDirDialog",0},
    { "_class_FXPyGLSphere","_FXPyGLSphere",0},
{0,0,0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initfoxc() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("foxc", foxcMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"MINKEY", PyInt_FromLong((long) 0));
	 PyDict_SetItemString(d,"MAXKEY", PyInt_FromLong((long) 65535));
	 PyDict_SetItemString(d,"MINTYPE", PyInt_FromLong((long) 0));
	 PyDict_SetItemString(d,"MAXTYPE", PyInt_FromLong((long) 65535));
	 PyDict_SetItemString(d,"SEL_NONE", PyInt_FromLong((long) SEL_NONE));
	 PyDict_SetItemString(d,"SEL_KEYPRESS", PyInt_FromLong((long) SEL_KEYPRESS));
	 PyDict_SetItemString(d,"SEL_KEYRELEASE", PyInt_FromLong((long) SEL_KEYRELEASE));
	 PyDict_SetItemString(d,"SEL_LEFTBUTTONPRESS", PyInt_FromLong((long) SEL_LEFTBUTTONPRESS));
	 PyDict_SetItemString(d,"SEL_LEFTBUTTONRELEASE", PyInt_FromLong((long) SEL_LEFTBUTTONRELEASE));
	 PyDict_SetItemString(d,"SEL_MIDDLEBUTTONPRESS", PyInt_FromLong((long) SEL_MIDDLEBUTTONPRESS));
	 PyDict_SetItemString(d,"SEL_MIDDLEBUTTONRELEASE", PyInt_FromLong((long) SEL_MIDDLEBUTTONRELEASE));
	 PyDict_SetItemString(d,"SEL_RIGHTBUTTONPRESS", PyInt_FromLong((long) SEL_RIGHTBUTTONPRESS));
	 PyDict_SetItemString(d,"SEL_RIGHTBUTTONRELEASE", PyInt_FromLong((long) SEL_RIGHTBUTTONRELEASE));
	 PyDict_SetItemString(d,"SEL_MOTION", PyInt_FromLong((long) SEL_MOTION));
	 PyDict_SetItemString(d,"SEL_ENTER", PyInt_FromLong((long) SEL_ENTER));
	 PyDict_SetItemString(d,"SEL_LEAVE", PyInt_FromLong((long) SEL_LEAVE));
	 PyDict_SetItemString(d,"SEL_FOCUSIN", PyInt_FromLong((long) SEL_FOCUSIN));
	 PyDict_SetItemString(d,"SEL_FOCUSOUT", PyInt_FromLong((long) SEL_FOCUSOUT));
	 PyDict_SetItemString(d,"SEL_KEYMAP", PyInt_FromLong((long) SEL_KEYMAP));
	 PyDict_SetItemString(d,"SEL_UNGRABBED", PyInt_FromLong((long) SEL_UNGRABBED));
	 PyDict_SetItemString(d,"SEL_PAINT", PyInt_FromLong((long) SEL_PAINT));
	 PyDict_SetItemString(d,"SEL_CREATE", PyInt_FromLong((long) SEL_CREATE));
	 PyDict_SetItemString(d,"SEL_DESTROY", PyInt_FromLong((long) SEL_DESTROY));
	 PyDict_SetItemString(d,"SEL_UNMAP", PyInt_FromLong((long) SEL_UNMAP));
	 PyDict_SetItemString(d,"SEL_MAP", PyInt_FromLong((long) SEL_MAP));
	 PyDict_SetItemString(d,"SEL_CONFIGURE", PyInt_FromLong((long) SEL_CONFIGURE));
	 PyDict_SetItemString(d,"SEL_SELECTION_LOST", PyInt_FromLong((long) SEL_SELECTION_LOST));
	 PyDict_SetItemString(d,"SEL_SELECTION_GAINED", PyInt_FromLong((long) SEL_SELECTION_GAINED));
	 PyDict_SetItemString(d,"SEL_SELECTION_REQUEST", PyInt_FromLong((long) SEL_SELECTION_REQUEST));
	 PyDict_SetItemString(d,"SEL_RAISED", PyInt_FromLong((long) SEL_RAISED));
	 PyDict_SetItemString(d,"SEL_LOWERED", PyInt_FromLong((long) SEL_LOWERED));
	 PyDict_SetItemString(d,"SEL_CLOSE", PyInt_FromLong((long) SEL_CLOSE));
	 PyDict_SetItemString(d,"SEL_CLOSEALL", PyInt_FromLong((long) SEL_CLOSEALL));
	 PyDict_SetItemString(d,"SEL_DELETE", PyInt_FromLong((long) SEL_DELETE));
	 PyDict_SetItemString(d,"SEL_MINIMIZE", PyInt_FromLong((long) SEL_MINIMIZE));
	 PyDict_SetItemString(d,"SEL_RESTORE", PyInt_FromLong((long) SEL_RESTORE));
	 PyDict_SetItemString(d,"SEL_MAXIMIZE", PyInt_FromLong((long) SEL_MAXIMIZE));
	 PyDict_SetItemString(d,"SEL_UPDATE", PyInt_FromLong((long) SEL_UPDATE));
	 PyDict_SetItemString(d,"SEL_COMMAND", PyInt_FromLong((long) SEL_COMMAND));
	 PyDict_SetItemString(d,"SEL_CLICKED", PyInt_FromLong((long) SEL_CLICKED));
	 PyDict_SetItemString(d,"SEL_DOUBLECLICKED", PyInt_FromLong((long) SEL_DOUBLECLICKED));
	 PyDict_SetItemString(d,"SEL_TRIPLECLICKED", PyInt_FromLong((long) SEL_TRIPLECLICKED));
	 PyDict_SetItemString(d,"SEL_MOUSEWHEEL", PyInt_FromLong((long) SEL_MOUSEWHEEL));
	 PyDict_SetItemString(d,"SEL_CHANGED", PyInt_FromLong((long) SEL_CHANGED));
	 PyDict_SetItemString(d,"SEL_VERIFY", PyInt_FromLong((long) SEL_VERIFY));
	 PyDict_SetItemString(d,"SEL_DESELECTED", PyInt_FromLong((long) SEL_DESELECTED));
	 PyDict_SetItemString(d,"SEL_SELECTED", PyInt_FromLong((long) SEL_SELECTED));
	 PyDict_SetItemString(d,"SEL_INSERTED", PyInt_FromLong((long) SEL_INSERTED));
	 PyDict_SetItemString(d,"SEL_REPLACED", PyInt_FromLong((long) SEL_REPLACED));
	 PyDict_SetItemString(d,"SEL_DELETED", PyInt_FromLong((long) SEL_DELETED));
	 PyDict_SetItemString(d,"SEL_OPENED", PyInt_FromLong((long) SEL_OPENED));
	 PyDict_SetItemString(d,"SEL_CLOSED", PyInt_FromLong((long) SEL_CLOSED));
	 PyDict_SetItemString(d,"SEL_EXPANDED", PyInt_FromLong((long) SEL_EXPANDED));
	 PyDict_SetItemString(d,"SEL_COLLAPSED", PyInt_FromLong((long) SEL_COLLAPSED));
	 PyDict_SetItemString(d,"SEL_BEGINDRAG", PyInt_FromLong((long) SEL_BEGINDRAG));
	 PyDict_SetItemString(d,"SEL_ENDDRAG", PyInt_FromLong((long) SEL_ENDDRAG));
	 PyDict_SetItemString(d,"SEL_DRAGGED", PyInt_FromLong((long) SEL_DRAGGED));
	 PyDict_SetItemString(d,"SEL_LASSOED", PyInt_FromLong((long) SEL_LASSOED));
	 PyDict_SetItemString(d,"SEL_TIMEOUT", PyInt_FromLong((long) SEL_TIMEOUT));
	 PyDict_SetItemString(d,"SEL_SIGNAL", PyInt_FromLong((long) SEL_SIGNAL));
	 PyDict_SetItemString(d,"SEL_CLIPBOARD_LOST", PyInt_FromLong((long) SEL_CLIPBOARD_LOST));
	 PyDict_SetItemString(d,"SEL_CLIPBOARD_GAINED", PyInt_FromLong((long) SEL_CLIPBOARD_GAINED));
	 PyDict_SetItemString(d,"SEL_CLIPBOARD_REQUEST", PyInt_FromLong((long) SEL_CLIPBOARD_REQUEST));
	 PyDict_SetItemString(d,"SEL_CHORE", PyInt_FromLong((long) SEL_CHORE));
	 PyDict_SetItemString(d,"SEL_FOCUS_SELF", PyInt_FromLong((long) SEL_FOCUS_SELF));
	 PyDict_SetItemString(d,"SEL_FOCUS_RIGHT", PyInt_FromLong((long) SEL_FOCUS_RIGHT));
	 PyDict_SetItemString(d,"SEL_FOCUS_LEFT", PyInt_FromLong((long) SEL_FOCUS_LEFT));
	 PyDict_SetItemString(d,"SEL_FOCUS_DOWN", PyInt_FromLong((long) SEL_FOCUS_DOWN));
	 PyDict_SetItemString(d,"SEL_FOCUS_UP", PyInt_FromLong((long) SEL_FOCUS_UP));
	 PyDict_SetItemString(d,"SEL_FOCUS_NEXT", PyInt_FromLong((long) SEL_FOCUS_NEXT));
	 PyDict_SetItemString(d,"SEL_FOCUS_PREV", PyInt_FromLong((long) SEL_FOCUS_PREV));
	 PyDict_SetItemString(d,"SEL_DND_ENTER", PyInt_FromLong((long) SEL_DND_ENTER));
	 PyDict_SetItemString(d,"SEL_DND_LEAVE", PyInt_FromLong((long) SEL_DND_LEAVE));
	 PyDict_SetItemString(d,"SEL_DND_DROP", PyInt_FromLong((long) SEL_DND_DROP));
	 PyDict_SetItemString(d,"SEL_DND_MOTION", PyInt_FromLong((long) SEL_DND_MOTION));
	 PyDict_SetItemString(d,"SEL_DND_REQUEST", PyInt_FromLong((long) SEL_DND_REQUEST));
	 PyDict_SetItemString(d,"SEL_UNCHECK_OTHER", PyInt_FromLong((long) SEL_UNCHECK_OTHER));
	 PyDict_SetItemString(d,"SEL_UNCHECK_RADIO", PyInt_FromLong((long) SEL_UNCHECK_RADIO));
	 PyDict_SetItemString(d,"SEL_IO_READ", PyInt_FromLong((long) SEL_IO_READ));
	 PyDict_SetItemString(d,"SEL_IO_WRITE", PyInt_FromLong((long) SEL_IO_WRITE));
	 PyDict_SetItemString(d,"SEL_IO_EXCEPT", PyInt_FromLong((long) SEL_IO_EXCEPT));
	 PyDict_SetItemString(d,"SEL_PICKED", PyInt_FromLong((long) SEL_PICKED));
	 PyDict_SetItemString(d,"SEL_LAST", PyInt_FromLong((long) SEL_LAST));
	 PyDict_SetItemString(d,"SHIFTMASK", PyInt_FromLong((long) SHIFTMASK));
	 PyDict_SetItemString(d,"CAPSLOCKMASK", PyInt_FromLong((long) CAPSLOCKMASK));
	 PyDict_SetItemString(d,"CONTROLMASK", PyInt_FromLong((long) CONTROLMASK));
	 PyDict_SetItemString(d,"ALTMASK", PyInt_FromLong((long) ALTMASK));
	 PyDict_SetItemString(d,"NUMLOCKMASK", PyInt_FromLong((long) NUMLOCKMASK));
	 PyDict_SetItemString(d,"SCROLLLOCKMASK", PyInt_FromLong((long) SCROLLLOCKMASK));
	 PyDict_SetItemString(d,"LEFTBUTTONMASK", PyInt_FromLong((long) LEFTBUTTONMASK));
	 PyDict_SetItemString(d,"MIDDLEBUTTONMASK", PyInt_FromLong((long) MIDDLEBUTTONMASK));
	 PyDict_SetItemString(d,"RIGHTBUTTONMASK", PyInt_FromLong((long) RIGHTBUTTONMASK));
	 PyDict_SetItemString(d,"LEFTBUTTON", PyInt_FromLong((long) LEFTBUTTON));
	 PyDict_SetItemString(d,"MIDDLEBUTTON", PyInt_FromLong((long) MIDDLEBUTTON));
	 PyDict_SetItemString(d,"RIGHTBUTTON", PyInt_FromLong((long) RIGHTBUTTON));
	 PyDict_SetItemString(d,"CROSSINGNORMAL", PyInt_FromLong((long) CROSSINGNORMAL));
	 PyDict_SetItemString(d,"CROSSINGGRAB", PyInt_FromLong((long) CROSSINGGRAB));
	 PyDict_SetItemString(d,"CROSSINGUNGRAB", PyInt_FromLong((long) CROSSINGUNGRAB));
	 PyDict_SetItemString(d,"VISIBILITYTOTAL", PyInt_FromLong((long) VISIBILITYTOTAL));
	 PyDict_SetItemString(d,"VISIBILITYPARTIAL", PyInt_FromLong((long) VISIBILITYPARTIAL));
	 PyDict_SetItemString(d,"VISIBILITYNONE", PyInt_FromLong((long) VISIBILITYNONE));
	 PyDict_SetItemString(d,"FILEMATCH_FILE_NAME", PyInt_FromLong((long) FILEMATCH_FILE_NAME));
	 PyDict_SetItemString(d,"FILEMATCH_NOESCAPE", PyInt_FromLong((long) FILEMATCH_NOESCAPE));
	 PyDict_SetItemString(d,"FILEMATCH_PERIOD", PyInt_FromLong((long) FILEMATCH_PERIOD));
	 PyDict_SetItemString(d,"FILEMATCH_LEADING_DIR", PyInt_FromLong((long) FILEMATCH_LEADING_DIR));
	 PyDict_SetItemString(d,"FILEMATCH_CASEFOLD", PyInt_FromLong((long) FILEMATCH_CASEFOLD));
	 PyDict_SetItemString(d,"DRAG_REJECT", PyInt_FromLong((long) DRAG_REJECT));
	 PyDict_SetItemString(d,"DRAG_ACCEPT", PyInt_FromLong((long) DRAG_ACCEPT));
	 PyDict_SetItemString(d,"DRAG_COPY", PyInt_FromLong((long) DRAG_COPY));
	 PyDict_SetItemString(d,"DRAG_MOVE", PyInt_FromLong((long) DRAG_MOVE));
	 PyDict_SetItemString(d,"DRAG_LINK", PyInt_FromLong((long) DRAG_LINK));
	 PyDict_SetItemString(d,"DRAG_PRIVATE", PyInt_FromLong((long) DRAG_PRIVATE));
	 PyDict_SetItemString(d,"FROM_SELECTION", PyInt_FromLong((long) FROM_SELECTION));
	 PyDict_SetItemString(d,"FROM_CLIPBOARD", PyInt_FromLong((long) FROM_CLIPBOARD));
	 PyDict_SetItemString(d,"FROM_DRAGNDROP", PyInt_FromLong((long) FROM_DRAGNDROP));
	 PyDict_SetItemString(d,"EXP_NEVER", PyInt_FromLong((long) EXP_NEVER));
	 PyDict_SetItemString(d,"EXP_ALWAYS", PyInt_FromLong((long) EXP_ALWAYS));
	 PyDict_SetItemString(d,"EXP_AUTO", PyInt_FromLong((long) EXP_AUTO));
	 PyDict_SetItemString(d,"SEARCH_FORWARD", PyInt_FromLong((long) SEARCH_FORWARD));
	 PyDict_SetItemString(d,"SEARCH_BACKWARD", PyInt_FromLong((long) SEARCH_BACKWARD));
	 PyDict_SetItemString(d,"SEARCH_NOWRAP", PyInt_FromLong((long) SEARCH_NOWRAP));
	 PyDict_SetItemString(d,"SEARCH_WRAP", PyInt_FromLong((long) SEARCH_WRAP));
	 PyDict_SetItemString(d,"SEARCH_EXACT", PyInt_FromLong((long) SEARCH_EXACT));
	 PyDict_SetItemString(d,"SEARCH_IGNORECASE", PyInt_FromLong((long) SEARCH_IGNORECASE));
	 PyDict_SetItemString(d,"SEARCH_REGEX", PyInt_FromLong((long) SEARCH_REGEX));
	 PyDict_SetItemString(d,"SEARCH_PREFIX", PyInt_FromLong((long) SEARCH_PREFIX));
	 PyDict_SetItemString(d,"FONTPITCH_DEFAULT", PyInt_FromLong((long) FONTPITCH_DEFAULT));
	 PyDict_SetItemString(d,"FONTPITCH_FIXED", PyInt_FromLong((long) FONTPITCH_FIXED));
	 PyDict_SetItemString(d,"FONTPITCH_VARIABLE", PyInt_FromLong((long) FONTPITCH_VARIABLE));
	 PyDict_SetItemString(d,"FONTHINT_DONTCARE", PyInt_FromLong((long) FONTHINT_DONTCARE));
	 PyDict_SetItemString(d,"FONTHINT_DECORATIVE", PyInt_FromLong((long) FONTHINT_DECORATIVE));
	 PyDict_SetItemString(d,"FONTHINT_MODERN", PyInt_FromLong((long) FONTHINT_MODERN));
	 PyDict_SetItemString(d,"FONTHINT_ROMAN", PyInt_FromLong((long) FONTHINT_ROMAN));
	 PyDict_SetItemString(d,"FONTHINT_SCRIPT", PyInt_FromLong((long) FONTHINT_SCRIPT));
	 PyDict_SetItemString(d,"FONTHINT_SWISS", PyInt_FromLong((long) FONTHINT_SWISS));
	 PyDict_SetItemString(d,"FONTHINT_SYSTEM", PyInt_FromLong((long) FONTHINT_SYSTEM));
	 PyDict_SetItemString(d,"FONTHINT_X11", PyInt_FromLong((long) FONTHINT_X11));
	 PyDict_SetItemString(d,"FONTHINT_SCALABLE", PyInt_FromLong((long) FONTHINT_SCALABLE));
	 PyDict_SetItemString(d,"FONTHINT_POLYMORPHIC", PyInt_FromLong((long) FONTHINT_POLYMORPHIC));
	 PyDict_SetItemString(d,"FONTSLANT_DONTCARE", PyInt_FromLong((long) FONTSLANT_DONTCARE));
	 PyDict_SetItemString(d,"FONTSLANT_REGULAR", PyInt_FromLong((long) FONTSLANT_REGULAR));
	 PyDict_SetItemString(d,"FONTSLANT_ITALIC", PyInt_FromLong((long) FONTSLANT_ITALIC));
	 PyDict_SetItemString(d,"FONTSLANT_OBLIQUE", PyInt_FromLong((long) FONTSLANT_OBLIQUE));
	 PyDict_SetItemString(d,"FONTSLANT_REVERSE_ITALIC", PyInt_FromLong((long) FONTSLANT_REVERSE_ITALIC));
	 PyDict_SetItemString(d,"FONTSLANT_REVERSE_OBLIQUE", PyInt_FromLong((long) FONTSLANT_REVERSE_OBLIQUE));
	 PyDict_SetItemString(d,"FONTENCODING_DEFAULT", PyInt_FromLong((long) FONTENCODING_DEFAULT));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_1", PyInt_FromLong((long) FONTENCODING_ISO_8859_1));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_2", PyInt_FromLong((long) FONTENCODING_ISO_8859_2));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_3", PyInt_FromLong((long) FONTENCODING_ISO_8859_3));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_4", PyInt_FromLong((long) FONTENCODING_ISO_8859_4));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_5", PyInt_FromLong((long) FONTENCODING_ISO_8859_5));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_6", PyInt_FromLong((long) FONTENCODING_ISO_8859_6));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_7", PyInt_FromLong((long) FONTENCODING_ISO_8859_7));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_8", PyInt_FromLong((long) FONTENCODING_ISO_8859_8));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_9", PyInt_FromLong((long) FONTENCODING_ISO_8859_9));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_10", PyInt_FromLong((long) FONTENCODING_ISO_8859_10));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_11", PyInt_FromLong((long) FONTENCODING_ISO_8859_11));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_13", PyInt_FromLong((long) FONTENCODING_ISO_8859_13));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_14", PyInt_FromLong((long) FONTENCODING_ISO_8859_14));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_15", PyInt_FromLong((long) FONTENCODING_ISO_8859_15));
	 PyDict_SetItemString(d,"FONTENCODING_ISO_8859_16", PyInt_FromLong((long) FONTENCODING_ISO_8859_16));
	 PyDict_SetItemString(d,"FONTENCODING_KOI8", PyInt_FromLong((long) FONTENCODING_KOI8));
	 PyDict_SetItemString(d,"FONTENCODING_KOI8_R", PyInt_FromLong((long) FONTENCODING_KOI8_R));
	 PyDict_SetItemString(d,"FONTENCODING_KOI8_U", PyInt_FromLong((long) FONTENCODING_KOI8_U));
	 PyDict_SetItemString(d,"FONTENCODING_KOI8_UNIFIED", PyInt_FromLong((long) FONTENCODING_KOI8_UNIFIED));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN1", PyInt_FromLong((long) FONTENCODING_LATIN1));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN2", PyInt_FromLong((long) FONTENCODING_LATIN2));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN3", PyInt_FromLong((long) FONTENCODING_LATIN3));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN4", PyInt_FromLong((long) FONTENCODING_LATIN4));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN5", PyInt_FromLong((long) FONTENCODING_LATIN5));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN6", PyInt_FromLong((long) FONTENCODING_LATIN6));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN7", PyInt_FromLong((long) FONTENCODING_LATIN7));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN8", PyInt_FromLong((long) FONTENCODING_LATIN8));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN9", PyInt_FromLong((long) FONTENCODING_LATIN9));
	 PyDict_SetItemString(d,"FONTENCODING_LATIN10", PyInt_FromLong((long) FONTENCODING_LATIN10));
	 PyDict_SetItemString(d,"FONTENCODING_USASCII", PyInt_FromLong((long) FONTENCODING_USASCII));
	 PyDict_SetItemString(d,"FONTENCODING_WESTEUROPE", PyInt_FromLong((long) FONTENCODING_WESTEUROPE));
	 PyDict_SetItemString(d,"FONTENCODING_EASTEUROPE", PyInt_FromLong((long) FONTENCODING_EASTEUROPE));
	 PyDict_SetItemString(d,"FONTENCODING_SOUTHEUROPE", PyInt_FromLong((long) FONTENCODING_SOUTHEUROPE));
	 PyDict_SetItemString(d,"FONTENCODING_NORTHEUROPE", PyInt_FromLong((long) FONTENCODING_NORTHEUROPE));
	 PyDict_SetItemString(d,"FONTENCODING_CYRILLIC", PyInt_FromLong((long) FONTENCODING_CYRILLIC));
	 PyDict_SetItemString(d,"FONTENCODING_RUSSIAN", PyInt_FromLong((long) FONTENCODING_RUSSIAN));
	 PyDict_SetItemString(d,"FONTENCODING_ARABIC", PyInt_FromLong((long) FONTENCODING_ARABIC));
	 PyDict_SetItemString(d,"FONTENCODING_GREEK", PyInt_FromLong((long) FONTENCODING_GREEK));
	 PyDict_SetItemString(d,"FONTENCODING_HEBREW", PyInt_FromLong((long) FONTENCODING_HEBREW));
	 PyDict_SetItemString(d,"FONTENCODING_TURKISH", PyInt_FromLong((long) FONTENCODING_TURKISH));
	 PyDict_SetItemString(d,"FONTENCODING_NORDIC", PyInt_FromLong((long) FONTENCODING_NORDIC));
	 PyDict_SetItemString(d,"FONTENCODING_THAI", PyInt_FromLong((long) FONTENCODING_THAI));
	 PyDict_SetItemString(d,"FONTENCODING_BALTIC", PyInt_FromLong((long) FONTENCODING_BALTIC));
	 PyDict_SetItemString(d,"FONTENCODING_CELTIC", PyInt_FromLong((long) FONTENCODING_CELTIC));
	 PyDict_SetItemString(d,"FONTWEIGHT_DONTCARE", PyInt_FromLong((long) FONTWEIGHT_DONTCARE));
	 PyDict_SetItemString(d,"FONTWEIGHT_THIN", PyInt_FromLong((long) FONTWEIGHT_THIN));
	 PyDict_SetItemString(d,"FONTWEIGHT_EXTRALIGHT", PyInt_FromLong((long) FONTWEIGHT_EXTRALIGHT));
	 PyDict_SetItemString(d,"FONTWEIGHT_LIGHT", PyInt_FromLong((long) FONTWEIGHT_LIGHT));
	 PyDict_SetItemString(d,"FONTWEIGHT_NORMAL", PyInt_FromLong((long) FONTWEIGHT_NORMAL));
	 PyDict_SetItemString(d,"FONTWEIGHT_REGULAR", PyInt_FromLong((long) FONTWEIGHT_REGULAR));
	 PyDict_SetItemString(d,"FONTWEIGHT_MEDIUM", PyInt_FromLong((long) FONTWEIGHT_MEDIUM));
	 PyDict_SetItemString(d,"FONTWEIGHT_DEMIBOLD", PyInt_FromLong((long) FONTWEIGHT_DEMIBOLD));
	 PyDict_SetItemString(d,"FONTWEIGHT_BOLD", PyInt_FromLong((long) FONTWEIGHT_BOLD));
	 PyDict_SetItemString(d,"FONTWEIGHT_EXTRABOLD", PyInt_FromLong((long) FONTWEIGHT_EXTRABOLD));
	 PyDict_SetItemString(d,"FONTWEIGHT_HEAVY", PyInt_FromLong((long) FONTWEIGHT_HEAVY));
	 PyDict_SetItemString(d,"FONTWEIGHT_BLACK", PyInt_FromLong((long) FONTWEIGHT_BLACK));
	 PyDict_SetItemString(d,"FONTSETWIDTH_DONTCARE", PyInt_FromLong((long) FONTSETWIDTH_DONTCARE));
	 PyDict_SetItemString(d,"FONTSETWIDTH_ULTRACONDENSED", PyInt_FromLong((long) FONTSETWIDTH_ULTRACONDENSED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_EXTRACONDENSED", PyInt_FromLong((long) FONTSETWIDTH_EXTRACONDENSED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_CONDENSED", PyInt_FromLong((long) FONTSETWIDTH_CONDENSED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_NARROW", PyInt_FromLong((long) FONTSETWIDTH_NARROW));
	 PyDict_SetItemString(d,"FONTSETWIDTH_COMPRESSED", PyInt_FromLong((long) FONTSETWIDTH_COMPRESSED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_SEMICONDENSED", PyInt_FromLong((long) FONTSETWIDTH_SEMICONDENSED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_MEDIUM", PyInt_FromLong((long) FONTSETWIDTH_MEDIUM));
	 PyDict_SetItemString(d,"FONTSETWIDTH_NORMAL", PyInt_FromLong((long) FONTSETWIDTH_NORMAL));
	 PyDict_SetItemString(d,"FONTSETWIDTH_REGULAR", PyInt_FromLong((long) FONTSETWIDTH_REGULAR));
	 PyDict_SetItemString(d,"FONTSETWIDTH_SEMIEXPANDED", PyInt_FromLong((long) FONTSETWIDTH_SEMIEXPANDED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_EXPANDED", PyInt_FromLong((long) FONTSETWIDTH_EXPANDED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_WIDE", PyInt_FromLong((long) FONTSETWIDTH_WIDE));
	 PyDict_SetItemString(d,"FONTSETWIDTH_EXTRAEXPANDED", PyInt_FromLong((long) FONTSETWIDTH_EXTRAEXPANDED));
	 PyDict_SetItemString(d,"FONTSETWIDTH_ULTRAEXPANDED", PyInt_FromLong((long) FONTSETWIDTH_ULTRAEXPANDED));
	 PyDict_SetItemString(d,"PRINT_DEST_PAPER", PyInt_FromLong((long) PRINT_DEST_PAPER));
	 PyDict_SetItemString(d,"PRINT_DEST_FILE", PyInt_FromLong((long) PRINT_DEST_FILE));
	 PyDict_SetItemString(d,"PRINT_PAGES_ALL", PyInt_FromLong((long) PRINT_PAGES_ALL));
	 PyDict_SetItemString(d,"PRINT_PAGES_EVEN", PyInt_FromLong((long) PRINT_PAGES_EVEN));
	 PyDict_SetItemString(d,"PRINT_PAGES_ODD", PyInt_FromLong((long) PRINT_PAGES_ODD));
	 PyDict_SetItemString(d,"PRINT_PAGES_RANGE", PyInt_FromLong((long) PRINT_PAGES_RANGE));
	 PyDict_SetItemString(d,"PRINT_COLLATE_NORMAL", PyInt_FromLong((long) PRINT_COLLATE_NORMAL));
	 PyDict_SetItemString(d,"PRINT_COLLATE_REVERSED", PyInt_FromLong((long) PRINT_COLLATE_REVERSED));
	 PyDict_SetItemString(d,"PRINT_PORTRAIT", PyInt_FromLong((long) PRINT_PORTRAIT));
	 PyDict_SetItemString(d,"PRINT_LANDSCAPE", PyInt_FromLong((long) PRINT_LANDSCAPE));
	 PyDict_SetItemString(d,"PRINT_BLACKANDWHITE", PyInt_FromLong((long) PRINT_BLACKANDWHITE));
	 PyDict_SetItemString(d,"PRINT_COLOR", PyInt_FromLong((long) PRINT_COLOR));
	 PyDict_SetItemString(d,"PRINT_NOBOUNDS", PyInt_FromLong((long) PRINT_NOBOUNDS));
	 PyDict_SetItemString(d,"MEDIA_CUSTOM", PyInt_FromLong((long) MEDIA_CUSTOM));
	 PyDict_SetItemString(d,"MEDIA_USLETTER", PyInt_FromLong((long) MEDIA_USLETTER));
	 PyDict_SetItemString(d,"MEDIA_LEGAL", PyInt_FromLong((long) MEDIA_LEGAL));
	 PyDict_SetItemString(d,"MEDIA_A4", PyInt_FromLong((long) MEDIA_A4));
	 PyDict_SetItemString(d,"MEDIA_ENVELOPE", PyInt_FromLong((long) MEDIA_ENVELOPE));
	 PyDict_SetItemString(d,"cvar", SWIG_globals);
	 SWIG_addvarlink(SWIG_globals,"fxTraceLevel",_wrap_fxTraceLevel_get, _wrap_fxTraceLevel_set);
	 SWIG_addvarlink(SWIG_globals,"messageTypeNames",_wrap_messageTypeNames_get, _wrap_messageTypeNames_set);

#ifdef FXPy_WITH_THREADS
    PyEval_InitThreads();
    extern PyThreadState *g_FXPyEventThreadState;
    g_FXPyEventThreadState = PyThreadState_Get();
#endif
    initcontainersc();
    initcontrolsc();
    initdialogsc();
    initdirlistc();
    initfox3dc();
    initgraphicsc();
    initiconlistc();
    initmdic();
    initmenusc();
    initmiscc();
    inittablec();
    inittextc();
    inittreelistc();
    initwindowsc();

    /* Register the array of message type names */
    FXPy_InitLists(d);
{
   int i;
   for (i = 0; _swig_mapping[i].n1; i++)
        SWIG_RegisterMapping(_swig_mapping[i].n1,_swig_mapping[i].n2,_swig_mapping[i].pcnv);
}
}
