# This file was created automatically by SWIG.
import foxc

class NullObj:
    this = 'NULL'

NULL = NullObj()


from misc import *

from graphics import *

from containers import *

from windows import *

from controls import *

from mdi import *

from menus import *

from dialogs import *

from treelist import *

from iconlist import *

from fox3d import *

from dirlist import *

from table import *

from text import *


#-------------- FUNCTION WRAPPERS ------------------

fxsleep = foxc.fxsleep

fxfilematch = foxc.fxfilematch

fxparseaccel = foxc.fxparseaccel

fxparsehotkey = foxc.fxparsehotkey

fxfindhotkeyoffset = foxc.fxfindhotkeyoffset

makeHiliteColor = foxc.makeHiliteColor

makeShadowColor = foxc.makeShadowColor

fxgetusername = foxc.fxgetusername

fxgetgroupname = foxc.fxgetgroupname

fxgetpermissions = foxc.fxgetpermissions

fxgetpid = foxc.fxgetpid

fxcolorfromname = foxc.fxcolorfromname

fxrgb_to_hsv = foxc.fxrgb_to_hsv

fxhsv_to_rgb = foxc.fxhsv_to_rgb

fxparsefontdesc = foxc.fxparsefontdesc

fxunparsefontdesc = foxc.fxunparsefontdesc

fxstrhash = foxc.fxstrhash

FXPySetDict = foxc.FXPySetDict

setErrorObject = foxc.setErrorObject

MKUINT = foxc.MKUINT

SELTYPE = foxc.SELTYPE

SELID = foxc.SELID

FXBITREVERSE = foxc.FXBITREVERSE

FXRGBA = foxc.FXRGBA

FXRGB = foxc.FXRGB

FXREDVAL = foxc.FXREDVAL

FXGREENVAL = foxc.FXGREENVAL

FXBLUEVAL = foxc.FXBLUEVAL

FXALPHAVAL = foxc.FXALPHAVAL

FXRGBACOMPVAL = foxc.FXRGBACOMPVAL



#-------------- VARIABLE WRAPPERS ------------------

MINKEY = foxc.MINKEY
MAXKEY = foxc.MAXKEY
MINTYPE = foxc.MINTYPE
MAXTYPE = foxc.MAXTYPE
SEL_NONE = foxc.SEL_NONE
SEL_KEYPRESS = foxc.SEL_KEYPRESS
SEL_KEYRELEASE = foxc.SEL_KEYRELEASE
SEL_LEFTBUTTONPRESS = foxc.SEL_LEFTBUTTONPRESS
SEL_LEFTBUTTONRELEASE = foxc.SEL_LEFTBUTTONRELEASE
SEL_MIDDLEBUTTONPRESS = foxc.SEL_MIDDLEBUTTONPRESS
SEL_MIDDLEBUTTONRELEASE = foxc.SEL_MIDDLEBUTTONRELEASE
SEL_RIGHTBUTTONPRESS = foxc.SEL_RIGHTBUTTONPRESS
SEL_RIGHTBUTTONRELEASE = foxc.SEL_RIGHTBUTTONRELEASE
SEL_MOTION = foxc.SEL_MOTION
SEL_ENTER = foxc.SEL_ENTER
SEL_LEAVE = foxc.SEL_LEAVE
SEL_FOCUSIN = foxc.SEL_FOCUSIN
SEL_FOCUSOUT = foxc.SEL_FOCUSOUT
SEL_KEYMAP = foxc.SEL_KEYMAP
SEL_UNGRABBED = foxc.SEL_UNGRABBED
SEL_PAINT = foxc.SEL_PAINT
SEL_CREATE = foxc.SEL_CREATE
SEL_DESTROY = foxc.SEL_DESTROY
SEL_UNMAP = foxc.SEL_UNMAP
SEL_MAP = foxc.SEL_MAP
SEL_CONFIGURE = foxc.SEL_CONFIGURE
SEL_SELECTION_LOST = foxc.SEL_SELECTION_LOST
SEL_SELECTION_GAINED = foxc.SEL_SELECTION_GAINED
SEL_SELECTION_REQUEST = foxc.SEL_SELECTION_REQUEST
SEL_RAISED = foxc.SEL_RAISED
SEL_LOWERED = foxc.SEL_LOWERED
SEL_CLOSE = foxc.SEL_CLOSE
SEL_CLOSEALL = foxc.SEL_CLOSEALL
SEL_DELETE = foxc.SEL_DELETE
SEL_MINIMIZE = foxc.SEL_MINIMIZE
SEL_RESTORE = foxc.SEL_RESTORE
SEL_MAXIMIZE = foxc.SEL_MAXIMIZE
SEL_UPDATE = foxc.SEL_UPDATE
SEL_COMMAND = foxc.SEL_COMMAND
SEL_CLICKED = foxc.SEL_CLICKED
SEL_DOUBLECLICKED = foxc.SEL_DOUBLECLICKED
SEL_TRIPLECLICKED = foxc.SEL_TRIPLECLICKED
SEL_MOUSEWHEEL = foxc.SEL_MOUSEWHEEL
SEL_CHANGED = foxc.SEL_CHANGED
SEL_VERIFY = foxc.SEL_VERIFY
SEL_DESELECTED = foxc.SEL_DESELECTED
SEL_SELECTED = foxc.SEL_SELECTED
SEL_INSERTED = foxc.SEL_INSERTED
SEL_REPLACED = foxc.SEL_REPLACED
SEL_DELETED = foxc.SEL_DELETED
SEL_OPENED = foxc.SEL_OPENED
SEL_CLOSED = foxc.SEL_CLOSED
SEL_EXPANDED = foxc.SEL_EXPANDED
SEL_COLLAPSED = foxc.SEL_COLLAPSED
SEL_BEGINDRAG = foxc.SEL_BEGINDRAG
SEL_ENDDRAG = foxc.SEL_ENDDRAG
SEL_DRAGGED = foxc.SEL_DRAGGED
SEL_LASSOED = foxc.SEL_LASSOED
SEL_TIMEOUT = foxc.SEL_TIMEOUT
SEL_SIGNAL = foxc.SEL_SIGNAL
SEL_CLIPBOARD_LOST = foxc.SEL_CLIPBOARD_LOST
SEL_CLIPBOARD_GAINED = foxc.SEL_CLIPBOARD_GAINED
SEL_CLIPBOARD_REQUEST = foxc.SEL_CLIPBOARD_REQUEST
SEL_CHORE = foxc.SEL_CHORE
SEL_FOCUS_SELF = foxc.SEL_FOCUS_SELF
SEL_FOCUS_RIGHT = foxc.SEL_FOCUS_RIGHT
SEL_FOCUS_LEFT = foxc.SEL_FOCUS_LEFT
SEL_FOCUS_DOWN = foxc.SEL_FOCUS_DOWN
SEL_FOCUS_UP = foxc.SEL_FOCUS_UP
SEL_FOCUS_NEXT = foxc.SEL_FOCUS_NEXT
SEL_FOCUS_PREV = foxc.SEL_FOCUS_PREV
SEL_DND_ENTER = foxc.SEL_DND_ENTER
SEL_DND_LEAVE = foxc.SEL_DND_LEAVE
SEL_DND_DROP = foxc.SEL_DND_DROP
SEL_DND_MOTION = foxc.SEL_DND_MOTION
SEL_DND_REQUEST = foxc.SEL_DND_REQUEST
SEL_UNCHECK_OTHER = foxc.SEL_UNCHECK_OTHER
SEL_UNCHECK_RADIO = foxc.SEL_UNCHECK_RADIO
SEL_IO_READ = foxc.SEL_IO_READ
SEL_IO_WRITE = foxc.SEL_IO_WRITE
SEL_IO_EXCEPT = foxc.SEL_IO_EXCEPT
SEL_PICKED = foxc.SEL_PICKED
SEL_LAST = foxc.SEL_LAST
SHIFTMASK = foxc.SHIFTMASK
CAPSLOCKMASK = foxc.CAPSLOCKMASK
CONTROLMASK = foxc.CONTROLMASK
ALTMASK = foxc.ALTMASK
NUMLOCKMASK = foxc.NUMLOCKMASK
SCROLLLOCKMASK = foxc.SCROLLLOCKMASK
LEFTBUTTONMASK = foxc.LEFTBUTTONMASK
MIDDLEBUTTONMASK = foxc.MIDDLEBUTTONMASK
RIGHTBUTTONMASK = foxc.RIGHTBUTTONMASK
LEFTBUTTON = foxc.LEFTBUTTON
MIDDLEBUTTON = foxc.MIDDLEBUTTON
RIGHTBUTTON = foxc.RIGHTBUTTON
CROSSINGNORMAL = foxc.CROSSINGNORMAL
CROSSINGGRAB = foxc.CROSSINGGRAB
CROSSINGUNGRAB = foxc.CROSSINGUNGRAB
VISIBILITYTOTAL = foxc.VISIBILITYTOTAL
VISIBILITYPARTIAL = foxc.VISIBILITYPARTIAL
VISIBILITYNONE = foxc.VISIBILITYNONE
FILEMATCH_FILE_NAME = foxc.FILEMATCH_FILE_NAME
FILEMATCH_NOESCAPE = foxc.FILEMATCH_NOESCAPE
FILEMATCH_PERIOD = foxc.FILEMATCH_PERIOD
FILEMATCH_LEADING_DIR = foxc.FILEMATCH_LEADING_DIR
FILEMATCH_CASEFOLD = foxc.FILEMATCH_CASEFOLD
DRAG_REJECT = foxc.DRAG_REJECT
DRAG_ACCEPT = foxc.DRAG_ACCEPT
DRAG_COPY = foxc.DRAG_COPY
DRAG_MOVE = foxc.DRAG_MOVE
DRAG_LINK = foxc.DRAG_LINK
DRAG_PRIVATE = foxc.DRAG_PRIVATE
FROM_SELECTION = foxc.FROM_SELECTION
FROM_CLIPBOARD = foxc.FROM_CLIPBOARD
FROM_DRAGNDROP = foxc.FROM_DRAGNDROP
EXP_NEVER = foxc.EXP_NEVER
EXP_ALWAYS = foxc.EXP_ALWAYS
EXP_AUTO = foxc.EXP_AUTO
SEARCH_FORWARD = foxc.SEARCH_FORWARD
SEARCH_BACKWARD = foxc.SEARCH_BACKWARD
SEARCH_NOWRAP = foxc.SEARCH_NOWRAP
SEARCH_WRAP = foxc.SEARCH_WRAP
SEARCH_EXACT = foxc.SEARCH_EXACT
SEARCH_IGNORECASE = foxc.SEARCH_IGNORECASE
SEARCH_REGEX = foxc.SEARCH_REGEX
SEARCH_PREFIX = foxc.SEARCH_PREFIX
FONTPITCH_DEFAULT = foxc.FONTPITCH_DEFAULT
FONTPITCH_FIXED = foxc.FONTPITCH_FIXED
FONTPITCH_VARIABLE = foxc.FONTPITCH_VARIABLE
FONTHINT_DONTCARE = foxc.FONTHINT_DONTCARE
FONTHINT_DECORATIVE = foxc.FONTHINT_DECORATIVE
FONTHINT_MODERN = foxc.FONTHINT_MODERN
FONTHINT_ROMAN = foxc.FONTHINT_ROMAN
FONTHINT_SCRIPT = foxc.FONTHINT_SCRIPT
FONTHINT_SWISS = foxc.FONTHINT_SWISS
FONTHINT_SYSTEM = foxc.FONTHINT_SYSTEM
FONTHINT_X11 = foxc.FONTHINT_X11
FONTHINT_SCALABLE = foxc.FONTHINT_SCALABLE
FONTHINT_POLYMORPHIC = foxc.FONTHINT_POLYMORPHIC
FONTSLANT_DONTCARE = foxc.FONTSLANT_DONTCARE
FONTSLANT_REGULAR = foxc.FONTSLANT_REGULAR
FONTSLANT_ITALIC = foxc.FONTSLANT_ITALIC
FONTSLANT_OBLIQUE = foxc.FONTSLANT_OBLIQUE
FONTSLANT_REVERSE_ITALIC = foxc.FONTSLANT_REVERSE_ITALIC
FONTSLANT_REVERSE_OBLIQUE = foxc.FONTSLANT_REVERSE_OBLIQUE
FONTENCODING_DEFAULT = foxc.FONTENCODING_DEFAULT
FONTENCODING_ISO_8859_1 = foxc.FONTENCODING_ISO_8859_1
FONTENCODING_ISO_8859_2 = foxc.FONTENCODING_ISO_8859_2
FONTENCODING_ISO_8859_3 = foxc.FONTENCODING_ISO_8859_3
FONTENCODING_ISO_8859_4 = foxc.FONTENCODING_ISO_8859_4
FONTENCODING_ISO_8859_5 = foxc.FONTENCODING_ISO_8859_5
FONTENCODING_ISO_8859_6 = foxc.FONTENCODING_ISO_8859_6
FONTENCODING_ISO_8859_7 = foxc.FONTENCODING_ISO_8859_7
FONTENCODING_ISO_8859_8 = foxc.FONTENCODING_ISO_8859_8
FONTENCODING_ISO_8859_9 = foxc.FONTENCODING_ISO_8859_9
FONTENCODING_ISO_8859_10 = foxc.FONTENCODING_ISO_8859_10
FONTENCODING_ISO_8859_11 = foxc.FONTENCODING_ISO_8859_11
FONTENCODING_ISO_8859_13 = foxc.FONTENCODING_ISO_8859_13
FONTENCODING_ISO_8859_14 = foxc.FONTENCODING_ISO_8859_14
FONTENCODING_ISO_8859_15 = foxc.FONTENCODING_ISO_8859_15
FONTENCODING_ISO_8859_16 = foxc.FONTENCODING_ISO_8859_16
FONTENCODING_KOI8 = foxc.FONTENCODING_KOI8
FONTENCODING_KOI8_R = foxc.FONTENCODING_KOI8_R
FONTENCODING_KOI8_U = foxc.FONTENCODING_KOI8_U
FONTENCODING_KOI8_UNIFIED = foxc.FONTENCODING_KOI8_UNIFIED
FONTENCODING_LATIN1 = foxc.FONTENCODING_LATIN1
FONTENCODING_LATIN2 = foxc.FONTENCODING_LATIN2
FONTENCODING_LATIN3 = foxc.FONTENCODING_LATIN3
FONTENCODING_LATIN4 = foxc.FONTENCODING_LATIN4
FONTENCODING_LATIN5 = foxc.FONTENCODING_LATIN5
FONTENCODING_LATIN6 = foxc.FONTENCODING_LATIN6
FONTENCODING_LATIN7 = foxc.FONTENCODING_LATIN7
FONTENCODING_LATIN8 = foxc.FONTENCODING_LATIN8
FONTENCODING_LATIN9 = foxc.FONTENCODING_LATIN9
FONTENCODING_LATIN10 = foxc.FONTENCODING_LATIN10
FONTENCODING_USASCII = foxc.FONTENCODING_USASCII
FONTENCODING_WESTEUROPE = foxc.FONTENCODING_WESTEUROPE
FONTENCODING_EASTEUROPE = foxc.FONTENCODING_EASTEUROPE
FONTENCODING_SOUTHEUROPE = foxc.FONTENCODING_SOUTHEUROPE
FONTENCODING_NORTHEUROPE = foxc.FONTENCODING_NORTHEUROPE
FONTENCODING_CYRILLIC = foxc.FONTENCODING_CYRILLIC
FONTENCODING_RUSSIAN = foxc.FONTENCODING_RUSSIAN
FONTENCODING_ARABIC = foxc.FONTENCODING_ARABIC
FONTENCODING_GREEK = foxc.FONTENCODING_GREEK
FONTENCODING_HEBREW = foxc.FONTENCODING_HEBREW
FONTENCODING_TURKISH = foxc.FONTENCODING_TURKISH
FONTENCODING_NORDIC = foxc.FONTENCODING_NORDIC
FONTENCODING_THAI = foxc.FONTENCODING_THAI
FONTENCODING_BALTIC = foxc.FONTENCODING_BALTIC
FONTENCODING_CELTIC = foxc.FONTENCODING_CELTIC
FONTWEIGHT_DONTCARE = foxc.FONTWEIGHT_DONTCARE
FONTWEIGHT_THIN = foxc.FONTWEIGHT_THIN
FONTWEIGHT_EXTRALIGHT = foxc.FONTWEIGHT_EXTRALIGHT
FONTWEIGHT_LIGHT = foxc.FONTWEIGHT_LIGHT
FONTWEIGHT_NORMAL = foxc.FONTWEIGHT_NORMAL
FONTWEIGHT_REGULAR = foxc.FONTWEIGHT_REGULAR
FONTWEIGHT_MEDIUM = foxc.FONTWEIGHT_MEDIUM
FONTWEIGHT_DEMIBOLD = foxc.FONTWEIGHT_DEMIBOLD
FONTWEIGHT_BOLD = foxc.FONTWEIGHT_BOLD
FONTWEIGHT_EXTRABOLD = foxc.FONTWEIGHT_EXTRABOLD
FONTWEIGHT_HEAVY = foxc.FONTWEIGHT_HEAVY
FONTWEIGHT_BLACK = foxc.FONTWEIGHT_BLACK
FONTSETWIDTH_DONTCARE = foxc.FONTSETWIDTH_DONTCARE
FONTSETWIDTH_ULTRACONDENSED = foxc.FONTSETWIDTH_ULTRACONDENSED
FONTSETWIDTH_EXTRACONDENSED = foxc.FONTSETWIDTH_EXTRACONDENSED
FONTSETWIDTH_CONDENSED = foxc.FONTSETWIDTH_CONDENSED
FONTSETWIDTH_NARROW = foxc.FONTSETWIDTH_NARROW
FONTSETWIDTH_COMPRESSED = foxc.FONTSETWIDTH_COMPRESSED
FONTSETWIDTH_SEMICONDENSED = foxc.FONTSETWIDTH_SEMICONDENSED
FONTSETWIDTH_MEDIUM = foxc.FONTSETWIDTH_MEDIUM
FONTSETWIDTH_NORMAL = foxc.FONTSETWIDTH_NORMAL
FONTSETWIDTH_REGULAR = foxc.FONTSETWIDTH_REGULAR
FONTSETWIDTH_SEMIEXPANDED = foxc.FONTSETWIDTH_SEMIEXPANDED
FONTSETWIDTH_EXPANDED = foxc.FONTSETWIDTH_EXPANDED
FONTSETWIDTH_WIDE = foxc.FONTSETWIDTH_WIDE
FONTSETWIDTH_EXTRAEXPANDED = foxc.FONTSETWIDTH_EXTRAEXPANDED
FONTSETWIDTH_ULTRAEXPANDED = foxc.FONTSETWIDTH_ULTRAEXPANDED
PRINT_DEST_PAPER = foxc.PRINT_DEST_PAPER
PRINT_DEST_FILE = foxc.PRINT_DEST_FILE
PRINT_PAGES_ALL = foxc.PRINT_PAGES_ALL
PRINT_PAGES_EVEN = foxc.PRINT_PAGES_EVEN
PRINT_PAGES_ODD = foxc.PRINT_PAGES_ODD
PRINT_PAGES_RANGE = foxc.PRINT_PAGES_RANGE
PRINT_COLLATE_NORMAL = foxc.PRINT_COLLATE_NORMAL
PRINT_COLLATE_REVERSED = foxc.PRINT_COLLATE_REVERSED
PRINT_PORTRAIT = foxc.PRINT_PORTRAIT
PRINT_LANDSCAPE = foxc.PRINT_LANDSCAPE
PRINT_BLACKANDWHITE = foxc.PRINT_BLACKANDWHITE
PRINT_COLOR = foxc.PRINT_COLOR
PRINT_NOBOUNDS = foxc.PRINT_NOBOUNDS
MEDIA_CUSTOM = foxc.MEDIA_CUSTOM
MEDIA_USLETTER = foxc.MEDIA_USLETTER
MEDIA_LEGAL = foxc.MEDIA_LEGAL
MEDIA_A4 = foxc.MEDIA_A4
MEDIA_ENVELOPE = foxc.MEDIA_ENVELOPE
cvar = foxc.cvar


#-------------- USER INCLUDE -----------------------

#
# Extra goodies appended to the end
#

# This call gives the C++ code layer access to Python's namespace
FXPySetDict(vars())

def FXMAPTYPES(self, typelo, typehi, func):
    if not hasattr(self, "FXMSGMAP"):
	self.FXMSGMAP = []
    keylo = MKUINT(MINKEY, typelo)
    keyhi = MKUINT(MAXKEY, typehi)
    tup = (keylo, keyhi, func)
    self.FXMSGMAP.append(tup)

def FXMAPTYPE(self, type, func):
    if not hasattr(self, "FXMSGMAP"):
	self.FXMSGMAP = []
    keylo = MKUINT(MINKEY, type)
    keyhi = MKUINT(MAXKEY, type)
    tup = (keylo, keyhi, func)
    self.FXMSGMAP.append(tup)

# Here's how we handle mapping message identifiers to method calls at
# the Python level. Each object instance has a list member called
# FXMSGMAP which maps a range of identifiers to a method call.
def FXMAPFUNC(self, type, id, func):
    if not hasattr(self, "FXMSGMAP"):
	self.FXMSGMAP = []
    keylo = MKUINT(id, type)
    keyhi = MKUINT(id, type)
    tup = (keylo, keyhi, func)
    self.FXMSGMAP.append(tup)

def FXMAPFUNCS(self, type, keylo, keyhi, func):
    if not hasattr(self, "FXMSGMAP"):
	self.FXMSGMAP = []
    keylo = MKUINT(keylo, type)
    keyhi = MKUINT(keyhi, type)
    tup = (keylo, keyhi, func)
    self.FXMSGMAP.append(tup)

